proto:
	python3 -m grpc_tools.protoc -I../../gRPC --python_out=. --grpc_python_out=. ../../gRPC/sdk_basic.proto
	python3 -m grpc_tools.protoc -I../../gRPC --python_out=. --grpc_python_out=. ../../gRPC/sdk_commands.proto
	python3 -m grpc_tools.protoc -I../../gRPC --python_out=. --grpc_python_out=. ../../gRPC/sdk_performer.proto