// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_basic.proto

package com.couchbase.grpc.sdk.protocol;

public interface BucketInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.BucketInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bucketName = 1;</code>
   * @return The bucketName.
   */
  java.lang.String getBucketName();
  /**
   * <code>string bucketName = 1;</code>
   * @return The bytes for bucketName.
   */
  com.google.protobuf.ByteString
      getBucketNameBytes();

  /**
   * <code>string scopeName = 2;</code>
   * @return The scopeName.
   */
  java.lang.String getScopeName();
  /**
   * <code>string scopeName = 2;</code>
   * @return The bytes for scopeName.
   */
  com.google.protobuf.ByteString
      getScopeNameBytes();

  /**
   * <code>string collectionName = 3;</code>
   * @return The collectionName.
   */
  java.lang.String getCollectionName();
  /**
   * <code>string collectionName = 3;</code>
   * @return The bytes for collectionName.
   */
  com.google.protobuf.ByteString
      getCollectionNameBytes();
}
