// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_commands.proto

package com.couchbase.grpc.sdk.protocol;

public interface CommandGetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.CommandGet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
   * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
   * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
   * </pre>
   *
   * <code>string docId = 1;</code>
   * @return The docId.
   */
  java.lang.String getDocId();
  /**
   * <pre>
   * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
   * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
   * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
   * </pre>
   *
   * <code>string docId = 1;</code>
   * @return The bytes for docId.
   */
  com.google.protobuf.ByteString
      getDocIdBytes();

  /**
   * <code>.protocol.BucketInfo bucketInfo = 2;</code>
   * @return Whether the bucketInfo field is set.
   */
  boolean hasBucketInfo();
  /**
   * <code>.protocol.BucketInfo bucketInfo = 2;</code>
   * @return The bucketInfo.
   */
  com.couchbase.grpc.sdk.protocol.BucketInfo getBucketInfo();
  /**
   * <code>.protocol.BucketInfo bucketInfo = 2;</code>
   */
  com.couchbase.grpc.sdk.protocol.BucketInfoOrBuilder getBucketInfoOrBuilder();
}
