// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_commands.proto

package com.couchbase.grpc.sdk.protocol;

public interface CommandInsertOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.CommandInsert)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protocol.BucketInfo bucketInfo = 3;</code>
   * @return Whether the bucketInfo field is set.
   */
  boolean hasBucketInfo();
  /**
   * <code>.protocol.BucketInfo bucketInfo = 3;</code>
   * @return The bucketInfo.
   */
  com.couchbase.grpc.sdk.protocol.BucketInfo getBucketInfo();
  /**
   * <code>.protocol.BucketInfo bucketInfo = 3;</code>
   */
  com.couchbase.grpc.sdk.protocol.BucketInfoOrBuilder getBucketInfoOrBuilder();

  /**
   * <code>string contentJson = 4;</code>
   * @return The contentJson.
   */
  java.lang.String getContentJson();
  /**
   * <code>string contentJson = 4;</code>
   * @return The bytes for contentJson.
   */
  com.google.protobuf.ByteString
      getContentJsonBytes();
}
