// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_commands.proto

package com.couchbase.grpc.sdk.protocol;

public interface CommandInsertOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.CommandInsert)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protocol.DocId docId = 1;</code>
   * @return Whether the docId field is set.
   */
  boolean hasDocId();
  /**
   * <code>.protocol.DocId docId = 1;</code>
   * @return The docId.
   */
  DocId getDocId();
  /**
   * <code>.protocol.DocId docId = 1;</code>
   */
  DocIdOrBuilder getDocIdOrBuilder();

  /**
   * <code>string contentJson = 2;</code>
   * @return The contentJson.
   */
  java.lang.String getContentJson();
  /**
   * <code>string contentJson = 2;</code>
   * @return The bytes for contentJson.
   */
  com.google.protobuf.ByteString
      getContentJsonBytes();
}
