// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_commands.proto

package com.couchbase.grpc.sdk.protocol;

/**
 * Protobuf type {@code protocol.CommandInsert}
 */
public final class CommandInsert extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.CommandInsert)
    CommandInsertOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CommandInsert.newBuilder() to construct.
  private CommandInsert(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommandInsert() {
    contentJson_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CommandInsert();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CommandInsert(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            DocId.Builder subBuilder = null;
            if (docId_ != null) {
              subBuilder = docId_.toBuilder();
            }
            docId_ = input.readMessage(DocId.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(docId_);
              docId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            contentJson_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SdkCommands.internal_static_protocol_CommandInsert_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SdkCommands.internal_static_protocol_CommandInsert_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CommandInsert.class, CommandInsert.Builder.class);
  }

  public static final int DOCID_FIELD_NUMBER = 1;
  private DocId docId_;
  /**
   * <code>.protocol.DocId docId = 1;</code>
   * @return Whether the docId field is set.
   */
  @java.lang.Override
  public boolean hasDocId() {
    return docId_ != null;
  }
  /**
   * <code>.protocol.DocId docId = 1;</code>
   * @return The docId.
   */
  @java.lang.Override
  public DocId getDocId() {
    return docId_ == null ? DocId.getDefaultInstance() : docId_;
  }
  /**
   * <code>.protocol.DocId docId = 1;</code>
   */
  @java.lang.Override
  public DocIdOrBuilder getDocIdOrBuilder() {
    return getDocId();
  }

  public static final int CONTENTJSON_FIELD_NUMBER = 2;
  private volatile java.lang.Object contentJson_;
  /**
   * <code>string contentJson = 2;</code>
   * @return The contentJson.
   */
  @java.lang.Override
  public java.lang.String getContentJson() {
    java.lang.Object ref = contentJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contentJson_ = s;
      return s;
    }
  }
  /**
   * <code>string contentJson = 2;</code>
   * @return The bytes for contentJson.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentJsonBytes() {
    java.lang.Object ref = contentJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contentJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (docId_ != null) {
      output.writeMessage(1, getDocId());
    }
    if (!getContentJsonBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, contentJson_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (docId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDocId());
    }
    if (!getContentJsonBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, contentJson_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CommandInsert)) {
      return super.equals(obj);
    }
    CommandInsert other = (CommandInsert) obj;

    if (hasDocId() != other.hasDocId()) return false;
    if (hasDocId()) {
      if (!getDocId()
          .equals(other.getDocId())) return false;
    }
    if (!getContentJson()
        .equals(other.getContentJson())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDocId()) {
      hash = (37 * hash) + DOCID_FIELD_NUMBER;
      hash = (53 * hash) + getDocId().hashCode();
    }
    hash = (37 * hash) + CONTENTJSON_FIELD_NUMBER;
    hash = (53 * hash) + getContentJson().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CommandInsert parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CommandInsert parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CommandInsert parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CommandInsert parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CommandInsert parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CommandInsert parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CommandInsert parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CommandInsert parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CommandInsert parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CommandInsert parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CommandInsert parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CommandInsert parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CommandInsert prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.CommandInsert}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.CommandInsert)
          CommandInsertOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SdkCommands.internal_static_protocol_CommandInsert_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SdkCommands.internal_static_protocol_CommandInsert_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CommandInsert.class, CommandInsert.Builder.class);
    }

    // Construct using com.couchbase.grpc.sdk.protocol.CommandInsert.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (docIdBuilder_ == null) {
        docId_ = null;
      } else {
        docId_ = null;
        docIdBuilder_ = null;
      }
      contentJson_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SdkCommands.internal_static_protocol_CommandInsert_descriptor;
    }

    @java.lang.Override
    public CommandInsert getDefaultInstanceForType() {
      return CommandInsert.getDefaultInstance();
    }

    @java.lang.Override
    public CommandInsert build() {
      CommandInsert result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public CommandInsert buildPartial() {
      CommandInsert result = new CommandInsert(this);
      if (docIdBuilder_ == null) {
        result.docId_ = docId_;
      } else {
        result.docId_ = docIdBuilder_.build();
      }
      result.contentJson_ = contentJson_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CommandInsert) {
        return mergeFrom((CommandInsert)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CommandInsert other) {
      if (other == CommandInsert.getDefaultInstance()) return this;
      if (other.hasDocId()) {
        mergeDocId(other.getDocId());
      }
      if (!other.getContentJson().isEmpty()) {
        contentJson_ = other.contentJson_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CommandInsert parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CommandInsert) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private DocId docId_;
    private com.google.protobuf.SingleFieldBuilderV3<
            DocId, DocId.Builder, DocIdOrBuilder> docIdBuilder_;
    /**
     * <code>.protocol.DocId docId = 1;</code>
     * @return Whether the docId field is set.
     */
    public boolean hasDocId() {
      return docIdBuilder_ != null || docId_ != null;
    }
    /**
     * <code>.protocol.DocId docId = 1;</code>
     * @return The docId.
     */
    public DocId getDocId() {
      if (docIdBuilder_ == null) {
        return docId_ == null ? DocId.getDefaultInstance() : docId_;
      } else {
        return docIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.protocol.DocId docId = 1;</code>
     */
    public Builder setDocId(DocId value) {
      if (docIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        docId_ = value;
        onChanged();
      } else {
        docIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.protocol.DocId docId = 1;</code>
     */
    public Builder setDocId(
        DocId.Builder builderForValue) {
      if (docIdBuilder_ == null) {
        docId_ = builderForValue.build();
        onChanged();
      } else {
        docIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.protocol.DocId docId = 1;</code>
     */
    public Builder mergeDocId(DocId value) {
      if (docIdBuilder_ == null) {
        if (docId_ != null) {
          docId_ =
            DocId.newBuilder(docId_).mergeFrom(value).buildPartial();
        } else {
          docId_ = value;
        }
        onChanged();
      } else {
        docIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.protocol.DocId docId = 1;</code>
     */
    public Builder clearDocId() {
      if (docIdBuilder_ == null) {
        docId_ = null;
        onChanged();
      } else {
        docId_ = null;
        docIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.protocol.DocId docId = 1;</code>
     */
    public DocId.Builder getDocIdBuilder() {
      
      onChanged();
      return getDocIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.protocol.DocId docId = 1;</code>
     */
    public DocIdOrBuilder getDocIdOrBuilder() {
      if (docIdBuilder_ != null) {
        return docIdBuilder_.getMessageOrBuilder();
      } else {
        return docId_ == null ?
            DocId.getDefaultInstance() : docId_;
      }
    }
    /**
     * <code>.protocol.DocId docId = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            DocId, DocId.Builder, DocIdOrBuilder>
        getDocIdFieldBuilder() {
      if (docIdBuilder_ == null) {
        docIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                DocId, DocId.Builder, DocIdOrBuilder>(
                getDocId(),
                getParentForChildren(),
                isClean());
        docId_ = null;
      }
      return docIdBuilder_;
    }

    private java.lang.Object contentJson_ = "";
    /**
     * <code>string contentJson = 2;</code>
     * @return The contentJson.
     */
    public java.lang.String getContentJson() {
      java.lang.Object ref = contentJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contentJson = 2;</code>
     * @return The bytes for contentJson.
     */
    public com.google.protobuf.ByteString
        getContentJsonBytes() {
      java.lang.Object ref = contentJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contentJson = 2;</code>
     * @param value The contentJson to set.
     * @return This builder for chaining.
     */
    public Builder setContentJson(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contentJson_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contentJson = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContentJson() {
      
      contentJson_ = getDefaultInstance().getContentJson();
      onChanged();
      return this;
    }
    /**
     * <code>string contentJson = 2;</code>
     * @param value The bytes for contentJson to set.
     * @return This builder for chaining.
     */
    public Builder setContentJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contentJson_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.CommandInsert)
  }

  // @@protoc_insertion_point(class_scope:protocol.CommandInsert)
  private static final CommandInsert DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CommandInsert();
  }

  public static CommandInsert getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommandInsert>
      PARSER = new com.google.protobuf.AbstractParser<CommandInsert>() {
    @java.lang.Override
    public CommandInsert parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CommandInsert(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CommandInsert> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommandInsert> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public CommandInsert getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

