// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_commands.proto

package com.couchbase.grpc.sdk.protocol;

/**
 * Protobuf type {@code protocol.CommandGet}
 */
public final class CommandGet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.CommandGet)
    CommandGetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CommandGet.newBuilder() to construct.
  private CommandGet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommandGet() {
    docId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CommandGet();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CommandGet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            docId_ = s;
            break;
          }
          case 18: {
            com.couchbase.grpc.sdk.protocol.BucketInfo.Builder subBuilder = null;
            if (bucketInfo_ != null) {
              subBuilder = bucketInfo_.toBuilder();
            }
            bucketInfo_ = input.readMessage(com.couchbase.grpc.sdk.protocol.BucketInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bucketInfo_);
              bucketInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.couchbase.grpc.sdk.protocol.SdkCommands.internal_static_protocol_CommandGet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.couchbase.grpc.sdk.protocol.SdkCommands.internal_static_protocol_CommandGet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.couchbase.grpc.sdk.protocol.CommandGet.class, com.couchbase.grpc.sdk.protocol.CommandGet.Builder.class);
  }

  public static final int DOCID_FIELD_NUMBER = 1;
  private volatile java.lang.Object docId_;
  /**
   * <pre>
   * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
   * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
   * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
   * </pre>
   *
   * <code>string docId = 1;</code>
   * @return The docId.
   */
  @java.lang.Override
  public java.lang.String getDocId() {
    java.lang.Object ref = docId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      docId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
   * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
   * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
   * </pre>
   *
   * <code>string docId = 1;</code>
   * @return The bytes for docId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDocIdBytes() {
    java.lang.Object ref = docId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      docId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUCKETINFO_FIELD_NUMBER = 2;
  private com.couchbase.grpc.sdk.protocol.BucketInfo bucketInfo_;
  /**
   * <code>.protocol.BucketInfo bucketInfo = 2;</code>
   * @return Whether the bucketInfo field is set.
   */
  @java.lang.Override
  public boolean hasBucketInfo() {
    return bucketInfo_ != null;
  }
  /**
   * <code>.protocol.BucketInfo bucketInfo = 2;</code>
   * @return The bucketInfo.
   */
  @java.lang.Override
  public com.couchbase.grpc.sdk.protocol.BucketInfo getBucketInfo() {
    return bucketInfo_ == null ? com.couchbase.grpc.sdk.protocol.BucketInfo.getDefaultInstance() : bucketInfo_;
  }
  /**
   * <code>.protocol.BucketInfo bucketInfo = 2;</code>
   */
  @java.lang.Override
  public com.couchbase.grpc.sdk.protocol.BucketInfoOrBuilder getBucketInfoOrBuilder() {
    return getBucketInfo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDocIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, docId_);
    }
    if (bucketInfo_ != null) {
      output.writeMessage(2, getBucketInfo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDocIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, docId_);
    }
    if (bucketInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBucketInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.couchbase.grpc.sdk.protocol.CommandGet)) {
      return super.equals(obj);
    }
    com.couchbase.grpc.sdk.protocol.CommandGet other = (com.couchbase.grpc.sdk.protocol.CommandGet) obj;

    if (!getDocId()
        .equals(other.getDocId())) return false;
    if (hasBucketInfo() != other.hasBucketInfo()) return false;
    if (hasBucketInfo()) {
      if (!getBucketInfo()
          .equals(other.getBucketInfo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DOCID_FIELD_NUMBER;
    hash = (53 * hash) + getDocId().hashCode();
    if (hasBucketInfo()) {
      hash = (37 * hash) + BUCKETINFO_FIELD_NUMBER;
      hash = (53 * hash) + getBucketInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.couchbase.grpc.sdk.protocol.CommandGet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.couchbase.grpc.sdk.protocol.CommandGet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.CommandGet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.couchbase.grpc.sdk.protocol.CommandGet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.CommandGet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.couchbase.grpc.sdk.protocol.CommandGet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.CommandGet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.couchbase.grpc.sdk.protocol.CommandGet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.CommandGet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.couchbase.grpc.sdk.protocol.CommandGet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.CommandGet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.couchbase.grpc.sdk.protocol.CommandGet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.couchbase.grpc.sdk.protocol.CommandGet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.CommandGet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.CommandGet)
      com.couchbase.grpc.sdk.protocol.CommandGetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.couchbase.grpc.sdk.protocol.SdkCommands.internal_static_protocol_CommandGet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.couchbase.grpc.sdk.protocol.SdkCommands.internal_static_protocol_CommandGet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.couchbase.grpc.sdk.protocol.CommandGet.class, com.couchbase.grpc.sdk.protocol.CommandGet.Builder.class);
    }

    // Construct using com.couchbase.grpc.sdk.protocol.CommandGet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      docId_ = "";

      if (bucketInfoBuilder_ == null) {
        bucketInfo_ = null;
      } else {
        bucketInfo_ = null;
        bucketInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.couchbase.grpc.sdk.protocol.SdkCommands.internal_static_protocol_CommandGet_descriptor;
    }

    @java.lang.Override
    public com.couchbase.grpc.sdk.protocol.CommandGet getDefaultInstanceForType() {
      return com.couchbase.grpc.sdk.protocol.CommandGet.getDefaultInstance();
    }

    @java.lang.Override
    public com.couchbase.grpc.sdk.protocol.CommandGet build() {
      com.couchbase.grpc.sdk.protocol.CommandGet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.couchbase.grpc.sdk.protocol.CommandGet buildPartial() {
      com.couchbase.grpc.sdk.protocol.CommandGet result = new com.couchbase.grpc.sdk.protocol.CommandGet(this);
      result.docId_ = docId_;
      if (bucketInfoBuilder_ == null) {
        result.bucketInfo_ = bucketInfo_;
      } else {
        result.bucketInfo_ = bucketInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.couchbase.grpc.sdk.protocol.CommandGet) {
        return mergeFrom((com.couchbase.grpc.sdk.protocol.CommandGet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.couchbase.grpc.sdk.protocol.CommandGet other) {
      if (other == com.couchbase.grpc.sdk.protocol.CommandGet.getDefaultInstance()) return this;
      if (!other.getDocId().isEmpty()) {
        docId_ = other.docId_;
        onChanged();
      }
      if (other.hasBucketInfo()) {
        mergeBucketInfo(other.getBucketInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.couchbase.grpc.sdk.protocol.CommandGet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.couchbase.grpc.sdk.protocol.CommandGet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object docId_ = "";
    /**
     * <pre>
     * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
     * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
     * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
     * </pre>
     *
     * <code>string docId = 1;</code>
     * @return The docId.
     */
    public java.lang.String getDocId() {
      java.lang.Object ref = docId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        docId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
     * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
     * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
     * </pre>
     *
     * <code>string docId = 1;</code>
     * @return The bytes for docId.
     */
    public com.google.protobuf.ByteString
        getDocIdBytes() {
      java.lang.Object ref = docId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        docId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
     * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
     * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
     * </pre>
     *
     * <code>string docId = 1;</code>
     * @param value The docId to set.
     * @return This builder for chaining.
     */
    public Builder setDocId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      docId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
     * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
     * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
     * </pre>
     *
     * <code>string docId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDocId() {
      
      docId_ = getDefaultInstance().getDocId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
     * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
     * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
     * </pre>
     *
     * <code>string docId = 1;</code>
     * @param value The bytes for docId to set.
     * @return This builder for chaining.
     */
    public Builder setDocIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      docId_ = value;
      onChanged();
      return this;
    }

    private com.couchbase.grpc.sdk.protocol.BucketInfo bucketInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.couchbase.grpc.sdk.protocol.BucketInfo, com.couchbase.grpc.sdk.protocol.BucketInfo.Builder, com.couchbase.grpc.sdk.protocol.BucketInfoOrBuilder> bucketInfoBuilder_;
    /**
     * <code>.protocol.BucketInfo bucketInfo = 2;</code>
     * @return Whether the bucketInfo field is set.
     */
    public boolean hasBucketInfo() {
      return bucketInfoBuilder_ != null || bucketInfo_ != null;
    }
    /**
     * <code>.protocol.BucketInfo bucketInfo = 2;</code>
     * @return The bucketInfo.
     */
    public com.couchbase.grpc.sdk.protocol.BucketInfo getBucketInfo() {
      if (bucketInfoBuilder_ == null) {
        return bucketInfo_ == null ? com.couchbase.grpc.sdk.protocol.BucketInfo.getDefaultInstance() : bucketInfo_;
      } else {
        return bucketInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.protocol.BucketInfo bucketInfo = 2;</code>
     */
    public Builder setBucketInfo(com.couchbase.grpc.sdk.protocol.BucketInfo value) {
      if (bucketInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bucketInfo_ = value;
        onChanged();
      } else {
        bucketInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.protocol.BucketInfo bucketInfo = 2;</code>
     */
    public Builder setBucketInfo(
        com.couchbase.grpc.sdk.protocol.BucketInfo.Builder builderForValue) {
      if (bucketInfoBuilder_ == null) {
        bucketInfo_ = builderForValue.build();
        onChanged();
      } else {
        bucketInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.protocol.BucketInfo bucketInfo = 2;</code>
     */
    public Builder mergeBucketInfo(com.couchbase.grpc.sdk.protocol.BucketInfo value) {
      if (bucketInfoBuilder_ == null) {
        if (bucketInfo_ != null) {
          bucketInfo_ =
            com.couchbase.grpc.sdk.protocol.BucketInfo.newBuilder(bucketInfo_).mergeFrom(value).buildPartial();
        } else {
          bucketInfo_ = value;
        }
        onChanged();
      } else {
        bucketInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.protocol.BucketInfo bucketInfo = 2;</code>
     */
    public Builder clearBucketInfo() {
      if (bucketInfoBuilder_ == null) {
        bucketInfo_ = null;
        onChanged();
      } else {
        bucketInfo_ = null;
        bucketInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.protocol.BucketInfo bucketInfo = 2;</code>
     */
    public com.couchbase.grpc.sdk.protocol.BucketInfo.Builder getBucketInfoBuilder() {
      
      onChanged();
      return getBucketInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.protocol.BucketInfo bucketInfo = 2;</code>
     */
    public com.couchbase.grpc.sdk.protocol.BucketInfoOrBuilder getBucketInfoOrBuilder() {
      if (bucketInfoBuilder_ != null) {
        return bucketInfoBuilder_.getMessageOrBuilder();
      } else {
        return bucketInfo_ == null ?
            com.couchbase.grpc.sdk.protocol.BucketInfo.getDefaultInstance() : bucketInfo_;
      }
    }
    /**
     * <code>.protocol.BucketInfo bucketInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.couchbase.grpc.sdk.protocol.BucketInfo, com.couchbase.grpc.sdk.protocol.BucketInfo.Builder, com.couchbase.grpc.sdk.protocol.BucketInfoOrBuilder> 
        getBucketInfoFieldBuilder() {
      if (bucketInfoBuilder_ == null) {
        bucketInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.couchbase.grpc.sdk.protocol.BucketInfo, com.couchbase.grpc.sdk.protocol.BucketInfo.Builder, com.couchbase.grpc.sdk.protocol.BucketInfoOrBuilder>(
                getBucketInfo(),
                getParentForChildren(),
                isClean());
        bucketInfo_ = null;
      }
      return bucketInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.CommandGet)
  }

  // @@protoc_insertion_point(class_scope:protocol.CommandGet)
  private static final com.couchbase.grpc.sdk.protocol.CommandGet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.couchbase.grpc.sdk.protocol.CommandGet();
  }

  public static com.couchbase.grpc.sdk.protocol.CommandGet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommandGet>
      PARSER = new com.google.protobuf.AbstractParser<CommandGet>() {
    @java.lang.Override
    public CommandGet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CommandGet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CommandGet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommandGet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.couchbase.grpc.sdk.protocol.CommandGet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

