// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_performer.proto

package com.couchbase.grpc.sdk.protocol;

public interface CreateConnectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.CreateConnectionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clusterHostname = 1;</code>
   * @return The clusterHostname.
   */
  java.lang.String getClusterHostname();
  /**
   * <code>string clusterHostname = 1;</code>
   * @return The bytes for clusterHostname.
   */
  com.google.protobuf.ByteString
      getClusterHostnameBytes();

  /**
   * <code>string clusterUsername = 2;</code>
   * @return The clusterUsername.
   */
  java.lang.String getClusterUsername();
  /**
   * <code>string clusterUsername = 2;</code>
   * @return The bytes for clusterUsername.
   */
  com.google.protobuf.ByteString
      getClusterUsernameBytes();

  /**
   * <code>string clusterPassword = 3;</code>
   * @return The clusterPassword.
   */
  java.lang.String getClusterPassword();
  /**
   * <code>string clusterPassword = 3;</code>
   * @return The bytes for clusterPassword.
   */
  com.google.protobuf.ByteString
      getClusterPasswordBytes();

  /**
   * <code>string bucketName = 4;</code>
   * @return The bucketName.
   */
  java.lang.String getBucketName();
  /**
   * <code>string bucketName = 4;</code>
   * @return The bytes for bucketName.
   */
  com.google.protobuf.ByteString
      getBucketNameBytes();

  /**
   * <code>bool useAsDefaultConnection = 5;</code>
   * @return The useAsDefaultConnection.
   */
  boolean getUseAsDefaultConnection();
}
