// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_performer.proto

package com.couchbase.grpc.sdk.protocol;

/**
 * <pre>
 * Returns the capabilities of the performer (or more specifically, the transactions-implementation-under-test by that
 * performer)
 *TODO: FIT equivalent is splitting this into two files, wait for that patchset to come through
 * </pre>
 *
 * Protobuf type {@code protocol.CreateConnectionResponse}
 */
public final class CreateConnectionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.CreateConnectionResponse)
    CreateConnectionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateConnectionResponse.newBuilder() to construct.
  private CreateConnectionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateConnectionResponse() {
    performerUserAgent_ = "";
    performerLibraryVersion_ = "";
    protocolVersion_ = "";
    clusterConnectionId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateConnectionResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateConnectionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            performerUserAgent_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            performerLibraryVersion_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            protocolVersion_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            clusterConnectionId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.couchbase.grpc.sdk.protocol.SdkPerformer.internal_static_protocol_CreateConnectionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.couchbase.grpc.sdk.protocol.SdkPerformer.internal_static_protocol_CreateConnectionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.couchbase.grpc.sdk.protocol.CreateConnectionResponse.class, com.couchbase.grpc.sdk.protocol.CreateConnectionResponse.Builder.class);
  }

  public static final int PERFORMERUSERAGENT_FIELD_NUMBER = 1;
  private volatile java.lang.Object performerUserAgent_;
  /**
   * <pre>
   * Human-readable string identifying the performer.  For example, "java".
   * </pre>
   *
   * <code>string performerUserAgent = 1;</code>
   * @return The performerUserAgent.
   */
  @java.lang.Override
  public java.lang.String getPerformerUserAgent() {
    java.lang.Object ref = performerUserAgent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      performerUserAgent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Human-readable string identifying the performer.  For example, "java".
   * </pre>
   *
   * <code>string performerUserAgent = 1;</code>
   * @return The bytes for performerUserAgent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPerformerUserAgentBytes() {
    java.lang.Object ref = performerUserAgent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      performerUserAgent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERFORMERLIBRARYVERSION_FIELD_NUMBER = 2;
  private volatile java.lang.Object performerLibraryVersion_;
  /**
   * <pre>
   * Identifies the version of the library under test.  For example, "1.1.2".
   * </pre>
   *
   * <code>string performerLibraryVersion = 2;</code>
   * @return The performerLibraryVersion.
   */
  @java.lang.Override
  public java.lang.String getPerformerLibraryVersion() {
    java.lang.Object ref = performerLibraryVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      performerLibraryVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Identifies the version of the library under test.  For example, "1.1.2".
   * </pre>
   *
   * <code>string performerLibraryVersion = 2;</code>
   * @return The bytes for performerLibraryVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPerformerLibraryVersionBytes() {
    java.lang.Object ref = performerLibraryVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      performerLibraryVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROTOCOLVERSION_FIELD_NUMBER = 3;
  private volatile java.lang.Object protocolVersion_;
  /**
   * <pre>
   * Defined https://hackmd.io/foGjnSSIQmqfks2lXwNp8w#Protocol-Versions
   * Must be "1.0" or "2.0", any other values will cause the driver to abort.
   * </pre>
   *
   * <code>string protocolVersion = 3;</code>
   * @return The protocolVersion.
   */
  @java.lang.Override
  public java.lang.String getProtocolVersion() {
    java.lang.Object ref = protocolVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      protocolVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Defined https://hackmd.io/foGjnSSIQmqfks2lXwNp8w#Protocol-Versions
   * Must be "1.0" or "2.0", any other values will cause the driver to abort.
   * </pre>
   *
   * <code>string protocolVersion = 3;</code>
   * @return The bytes for protocolVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProtocolVersionBytes() {
    java.lang.Object ref = protocolVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      protocolVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLUSTERCONNECTIONID_FIELD_NUMBER = 4;
  private volatile java.lang.Object clusterConnectionId_;
  /**
   * <code>string clusterConnectionId = 4;</code>
   * @return The clusterConnectionId.
   */
  @java.lang.Override
  public java.lang.String getClusterConnectionId() {
    java.lang.Object ref = clusterConnectionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clusterConnectionId_ = s;
      return s;
    }
  }
  /**
   * <code>string clusterConnectionId = 4;</code>
   * @return The bytes for clusterConnectionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClusterConnectionIdBytes() {
    java.lang.Object ref = clusterConnectionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clusterConnectionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPerformerUserAgentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, performerUserAgent_);
    }
    if (!getPerformerLibraryVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, performerLibraryVersion_);
    }
    if (!getProtocolVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, protocolVersion_);
    }
    if (!getClusterConnectionIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, clusterConnectionId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPerformerUserAgentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, performerUserAgent_);
    }
    if (!getPerformerLibraryVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, performerLibraryVersion_);
    }
    if (!getProtocolVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, protocolVersion_);
    }
    if (!getClusterConnectionIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, clusterConnectionId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.couchbase.grpc.sdk.protocol.CreateConnectionResponse)) {
      return super.equals(obj);
    }
    com.couchbase.grpc.sdk.protocol.CreateConnectionResponse other = (com.couchbase.grpc.sdk.protocol.CreateConnectionResponse) obj;

    if (!getPerformerUserAgent()
        .equals(other.getPerformerUserAgent())) return false;
    if (!getPerformerLibraryVersion()
        .equals(other.getPerformerLibraryVersion())) return false;
    if (!getProtocolVersion()
        .equals(other.getProtocolVersion())) return false;
    if (!getClusterConnectionId()
        .equals(other.getClusterConnectionId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PERFORMERUSERAGENT_FIELD_NUMBER;
    hash = (53 * hash) + getPerformerUserAgent().hashCode();
    hash = (37 * hash) + PERFORMERLIBRARYVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getPerformerLibraryVersion().hashCode();
    hash = (37 * hash) + PROTOCOLVERSION_FIELD_NUMBER;
    hash = (53 * hash) + getProtocolVersion().hashCode();
    hash = (37 * hash) + CLUSTERCONNECTIONID_FIELD_NUMBER;
    hash = (53 * hash) + getClusterConnectionId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.couchbase.grpc.sdk.protocol.CreateConnectionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.couchbase.grpc.sdk.protocol.CreateConnectionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Returns the capabilities of the performer (or more specifically, the transactions-implementation-under-test by that
   * performer)
   *TODO: FIT equivalent is splitting this into two files, wait for that patchset to come through
   * </pre>
   *
   * Protobuf type {@code protocol.CreateConnectionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.CreateConnectionResponse)
      com.couchbase.grpc.sdk.protocol.CreateConnectionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.couchbase.grpc.sdk.protocol.SdkPerformer.internal_static_protocol_CreateConnectionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.couchbase.grpc.sdk.protocol.SdkPerformer.internal_static_protocol_CreateConnectionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.couchbase.grpc.sdk.protocol.CreateConnectionResponse.class, com.couchbase.grpc.sdk.protocol.CreateConnectionResponse.Builder.class);
    }

    // Construct using com.couchbase.grpc.sdk.protocol.CreateConnectionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      performerUserAgent_ = "";

      performerLibraryVersion_ = "";

      protocolVersion_ = "";

      clusterConnectionId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.couchbase.grpc.sdk.protocol.SdkPerformer.internal_static_protocol_CreateConnectionResponse_descriptor;
    }

    @java.lang.Override
    public com.couchbase.grpc.sdk.protocol.CreateConnectionResponse getDefaultInstanceForType() {
      return com.couchbase.grpc.sdk.protocol.CreateConnectionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.couchbase.grpc.sdk.protocol.CreateConnectionResponse build() {
      com.couchbase.grpc.sdk.protocol.CreateConnectionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.couchbase.grpc.sdk.protocol.CreateConnectionResponse buildPartial() {
      com.couchbase.grpc.sdk.protocol.CreateConnectionResponse result = new com.couchbase.grpc.sdk.protocol.CreateConnectionResponse(this);
      result.performerUserAgent_ = performerUserAgent_;
      result.performerLibraryVersion_ = performerLibraryVersion_;
      result.protocolVersion_ = protocolVersion_;
      result.clusterConnectionId_ = clusterConnectionId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.couchbase.grpc.sdk.protocol.CreateConnectionResponse) {
        return mergeFrom((com.couchbase.grpc.sdk.protocol.CreateConnectionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.couchbase.grpc.sdk.protocol.CreateConnectionResponse other) {
      if (other == com.couchbase.grpc.sdk.protocol.CreateConnectionResponse.getDefaultInstance()) return this;
      if (!other.getPerformerUserAgent().isEmpty()) {
        performerUserAgent_ = other.performerUserAgent_;
        onChanged();
      }
      if (!other.getPerformerLibraryVersion().isEmpty()) {
        performerLibraryVersion_ = other.performerLibraryVersion_;
        onChanged();
      }
      if (!other.getProtocolVersion().isEmpty()) {
        protocolVersion_ = other.protocolVersion_;
        onChanged();
      }
      if (!other.getClusterConnectionId().isEmpty()) {
        clusterConnectionId_ = other.clusterConnectionId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.couchbase.grpc.sdk.protocol.CreateConnectionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.couchbase.grpc.sdk.protocol.CreateConnectionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object performerUserAgent_ = "";
    /**
     * <pre>
     * Human-readable string identifying the performer.  For example, "java".
     * </pre>
     *
     * <code>string performerUserAgent = 1;</code>
     * @return The performerUserAgent.
     */
    public java.lang.String getPerformerUserAgent() {
      java.lang.Object ref = performerUserAgent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        performerUserAgent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Human-readable string identifying the performer.  For example, "java".
     * </pre>
     *
     * <code>string performerUserAgent = 1;</code>
     * @return The bytes for performerUserAgent.
     */
    public com.google.protobuf.ByteString
        getPerformerUserAgentBytes() {
      java.lang.Object ref = performerUserAgent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        performerUserAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Human-readable string identifying the performer.  For example, "java".
     * </pre>
     *
     * <code>string performerUserAgent = 1;</code>
     * @param value The performerUserAgent to set.
     * @return This builder for chaining.
     */
    public Builder setPerformerUserAgent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      performerUserAgent_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Human-readable string identifying the performer.  For example, "java".
     * </pre>
     *
     * <code>string performerUserAgent = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPerformerUserAgent() {
      
      performerUserAgent_ = getDefaultInstance().getPerformerUserAgent();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Human-readable string identifying the performer.  For example, "java".
     * </pre>
     *
     * <code>string performerUserAgent = 1;</code>
     * @param value The bytes for performerUserAgent to set.
     * @return This builder for chaining.
     */
    public Builder setPerformerUserAgentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      performerUserAgent_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object performerLibraryVersion_ = "";
    /**
     * <pre>
     * Identifies the version of the library under test.  For example, "1.1.2".
     * </pre>
     *
     * <code>string performerLibraryVersion = 2;</code>
     * @return The performerLibraryVersion.
     */
    public java.lang.String getPerformerLibraryVersion() {
      java.lang.Object ref = performerLibraryVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        performerLibraryVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Identifies the version of the library under test.  For example, "1.1.2".
     * </pre>
     *
     * <code>string performerLibraryVersion = 2;</code>
     * @return The bytes for performerLibraryVersion.
     */
    public com.google.protobuf.ByteString
        getPerformerLibraryVersionBytes() {
      java.lang.Object ref = performerLibraryVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        performerLibraryVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Identifies the version of the library under test.  For example, "1.1.2".
     * </pre>
     *
     * <code>string performerLibraryVersion = 2;</code>
     * @param value The performerLibraryVersion to set.
     * @return This builder for chaining.
     */
    public Builder setPerformerLibraryVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      performerLibraryVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifies the version of the library under test.  For example, "1.1.2".
     * </pre>
     *
     * <code>string performerLibraryVersion = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPerformerLibraryVersion() {
      
      performerLibraryVersion_ = getDefaultInstance().getPerformerLibraryVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifies the version of the library under test.  For example, "1.1.2".
     * </pre>
     *
     * <code>string performerLibraryVersion = 2;</code>
     * @param value The bytes for performerLibraryVersion to set.
     * @return This builder for chaining.
     */
    public Builder setPerformerLibraryVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      performerLibraryVersion_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object protocolVersion_ = "";
    /**
     * <pre>
     * Defined https://hackmd.io/foGjnSSIQmqfks2lXwNp8w#Protocol-Versions
     * Must be "1.0" or "2.0", any other values will cause the driver to abort.
     * </pre>
     *
     * <code>string protocolVersion = 3;</code>
     * @return The protocolVersion.
     */
    public java.lang.String getProtocolVersion() {
      java.lang.Object ref = protocolVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        protocolVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Defined https://hackmd.io/foGjnSSIQmqfks2lXwNp8w#Protocol-Versions
     * Must be "1.0" or "2.0", any other values will cause the driver to abort.
     * </pre>
     *
     * <code>string protocolVersion = 3;</code>
     * @return The bytes for protocolVersion.
     */
    public com.google.protobuf.ByteString
        getProtocolVersionBytes() {
      java.lang.Object ref = protocolVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protocolVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Defined https://hackmd.io/foGjnSSIQmqfks2lXwNp8w#Protocol-Versions
     * Must be "1.0" or "2.0", any other values will cause the driver to abort.
     * </pre>
     *
     * <code>string protocolVersion = 3;</code>
     * @param value The protocolVersion to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protocolVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Defined https://hackmd.io/foGjnSSIQmqfks2lXwNp8w#Protocol-Versions
     * Must be "1.0" or "2.0", any other values will cause the driver to abort.
     * </pre>
     *
     * <code>string protocolVersion = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocolVersion() {
      
      protocolVersion_ = getDefaultInstance().getProtocolVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Defined https://hackmd.io/foGjnSSIQmqfks2lXwNp8w#Protocol-Versions
     * Must be "1.0" or "2.0", any other values will cause the driver to abort.
     * </pre>
     *
     * <code>string protocolVersion = 3;</code>
     * @param value The bytes for protocolVersion to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      protocolVersion_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object clusterConnectionId_ = "";
    /**
     * <code>string clusterConnectionId = 4;</code>
     * @return The clusterConnectionId.
     */
    public java.lang.String getClusterConnectionId() {
      java.lang.Object ref = clusterConnectionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clusterConnectionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clusterConnectionId = 4;</code>
     * @return The bytes for clusterConnectionId.
     */
    public com.google.protobuf.ByteString
        getClusterConnectionIdBytes() {
      java.lang.Object ref = clusterConnectionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusterConnectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clusterConnectionId = 4;</code>
     * @param value The clusterConnectionId to set.
     * @return This builder for chaining.
     */
    public Builder setClusterConnectionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clusterConnectionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clusterConnectionId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearClusterConnectionId() {
      
      clusterConnectionId_ = getDefaultInstance().getClusterConnectionId();
      onChanged();
      return this;
    }
    /**
     * <code>string clusterConnectionId = 4;</code>
     * @param value The bytes for clusterConnectionId to set.
     * @return This builder for chaining.
     */
    public Builder setClusterConnectionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clusterConnectionId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.CreateConnectionResponse)
  }

  // @@protoc_insertion_point(class_scope:protocol.CreateConnectionResponse)
  private static final com.couchbase.grpc.sdk.protocol.CreateConnectionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.couchbase.grpc.sdk.protocol.CreateConnectionResponse();
  }

  public static com.couchbase.grpc.sdk.protocol.CreateConnectionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateConnectionResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateConnectionResponse>() {
    @java.lang.Override
    public CreateConnectionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateConnectionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateConnectionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateConnectionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.couchbase.grpc.sdk.protocol.CreateConnectionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

