// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_performer.proto

package com.couchbase.grpc.sdk.protocol;

/**
 * Protobuf type {@code protocol.CreateConnectionRequest}
 */
public final class CreateConnectionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.CreateConnectionRequest)
    CreateConnectionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateConnectionRequest.newBuilder() to construct.
  private CreateConnectionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateConnectionRequest() {
    clusterHostname_ = "";
    clusterUsername_ = "";
    clusterPassword_ = "";
    bucketName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateConnectionRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateConnectionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            clusterHostname_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            clusterUsername_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            clusterPassword_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            bucketName_ = s;
            break;
          }
          case 40: {

            useAsDefaultConnection_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.couchbase.grpc.sdk.protocol.SdkPerformer.internal_static_protocol_CreateConnectionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.couchbase.grpc.sdk.protocol.SdkPerformer.internal_static_protocol_CreateConnectionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.couchbase.grpc.sdk.protocol.CreateConnectionRequest.class, com.couchbase.grpc.sdk.protocol.CreateConnectionRequest.Builder.class);
  }

  public static final int CLUSTERHOSTNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object clusterHostname_;
  /**
   * <code>string clusterHostname = 1;</code>
   * @return The clusterHostname.
   */
  @java.lang.Override
  public java.lang.String getClusterHostname() {
    java.lang.Object ref = clusterHostname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clusterHostname_ = s;
      return s;
    }
  }
  /**
   * <code>string clusterHostname = 1;</code>
   * @return The bytes for clusterHostname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClusterHostnameBytes() {
    java.lang.Object ref = clusterHostname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clusterHostname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLUSTERUSERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object clusterUsername_;
  /**
   * <code>string clusterUsername = 2;</code>
   * @return The clusterUsername.
   */
  @java.lang.Override
  public java.lang.String getClusterUsername() {
    java.lang.Object ref = clusterUsername_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clusterUsername_ = s;
      return s;
    }
  }
  /**
   * <code>string clusterUsername = 2;</code>
   * @return The bytes for clusterUsername.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClusterUsernameBytes() {
    java.lang.Object ref = clusterUsername_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clusterUsername_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLUSTERPASSWORD_FIELD_NUMBER = 3;
  private volatile java.lang.Object clusterPassword_;
  /**
   * <code>string clusterPassword = 3;</code>
   * @return The clusterPassword.
   */
  @java.lang.Override
  public java.lang.String getClusterPassword() {
    java.lang.Object ref = clusterPassword_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clusterPassword_ = s;
      return s;
    }
  }
  /**
   * <code>string clusterPassword = 3;</code>
   * @return The bytes for clusterPassword.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClusterPasswordBytes() {
    java.lang.Object ref = clusterPassword_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clusterPassword_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUCKETNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object bucketName_;
  /**
   * <code>string bucketName = 4;</code>
   * @return The bucketName.
   */
  @java.lang.Override
  public java.lang.String getBucketName() {
    java.lang.Object ref = bucketName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bucketName_ = s;
      return s;
    }
  }
  /**
   * <code>string bucketName = 4;</code>
   * @return The bytes for bucketName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBucketNameBytes() {
    java.lang.Object ref = bucketName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bucketName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USEASDEFAULTCONNECTION_FIELD_NUMBER = 5;
  private boolean useAsDefaultConnection_;
  /**
   * <code>bool useAsDefaultConnection = 5;</code>
   * @return The useAsDefaultConnection.
   */
  @java.lang.Override
  public boolean getUseAsDefaultConnection() {
    return useAsDefaultConnection_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClusterHostnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clusterHostname_);
    }
    if (!getClusterUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clusterUsername_);
    }
    if (!getClusterPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clusterPassword_);
    }
    if (!getBucketNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, bucketName_);
    }
    if (useAsDefaultConnection_ != false) {
      output.writeBool(5, useAsDefaultConnection_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClusterHostnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clusterHostname_);
    }
    if (!getClusterUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clusterUsername_);
    }
    if (!getClusterPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clusterPassword_);
    }
    if (!getBucketNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, bucketName_);
    }
    if (useAsDefaultConnection_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, useAsDefaultConnection_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.couchbase.grpc.sdk.protocol.CreateConnectionRequest)) {
      return super.equals(obj);
    }
    com.couchbase.grpc.sdk.protocol.CreateConnectionRequest other = (com.couchbase.grpc.sdk.protocol.CreateConnectionRequest) obj;

    if (!getClusterHostname()
        .equals(other.getClusterHostname())) return false;
    if (!getClusterUsername()
        .equals(other.getClusterUsername())) return false;
    if (!getClusterPassword()
        .equals(other.getClusterPassword())) return false;
    if (!getBucketName()
        .equals(other.getBucketName())) return false;
    if (getUseAsDefaultConnection()
        != other.getUseAsDefaultConnection()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLUSTERHOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getClusterHostname().hashCode();
    hash = (37 * hash) + CLUSTERUSERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getClusterUsername().hashCode();
    hash = (37 * hash) + CLUSTERPASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getClusterPassword().hashCode();
    hash = (37 * hash) + BUCKETNAME_FIELD_NUMBER;
    hash = (53 * hash) + getBucketName().hashCode();
    hash = (37 * hash) + USEASDEFAULTCONNECTION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getUseAsDefaultConnection());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.couchbase.grpc.sdk.protocol.CreateConnectionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.couchbase.grpc.sdk.protocol.CreateConnectionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.couchbase.grpc.sdk.protocol.CreateConnectionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.CreateConnectionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.CreateConnectionRequest)
      com.couchbase.grpc.sdk.protocol.CreateConnectionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.couchbase.grpc.sdk.protocol.SdkPerformer.internal_static_protocol_CreateConnectionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.couchbase.grpc.sdk.protocol.SdkPerformer.internal_static_protocol_CreateConnectionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.couchbase.grpc.sdk.protocol.CreateConnectionRequest.class, com.couchbase.grpc.sdk.protocol.CreateConnectionRequest.Builder.class);
    }

    // Construct using com.couchbase.grpc.sdk.protocol.CreateConnectionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clusterHostname_ = "";

      clusterUsername_ = "";

      clusterPassword_ = "";

      bucketName_ = "";

      useAsDefaultConnection_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.couchbase.grpc.sdk.protocol.SdkPerformer.internal_static_protocol_CreateConnectionRequest_descriptor;
    }

    @java.lang.Override
    public com.couchbase.grpc.sdk.protocol.CreateConnectionRequest getDefaultInstanceForType() {
      return com.couchbase.grpc.sdk.protocol.CreateConnectionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.couchbase.grpc.sdk.protocol.CreateConnectionRequest build() {
      com.couchbase.grpc.sdk.protocol.CreateConnectionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.couchbase.grpc.sdk.protocol.CreateConnectionRequest buildPartial() {
      com.couchbase.grpc.sdk.protocol.CreateConnectionRequest result = new com.couchbase.grpc.sdk.protocol.CreateConnectionRequest(this);
      result.clusterHostname_ = clusterHostname_;
      result.clusterUsername_ = clusterUsername_;
      result.clusterPassword_ = clusterPassword_;
      result.bucketName_ = bucketName_;
      result.useAsDefaultConnection_ = useAsDefaultConnection_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.couchbase.grpc.sdk.protocol.CreateConnectionRequest) {
        return mergeFrom((com.couchbase.grpc.sdk.protocol.CreateConnectionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.couchbase.grpc.sdk.protocol.CreateConnectionRequest other) {
      if (other == com.couchbase.grpc.sdk.protocol.CreateConnectionRequest.getDefaultInstance()) return this;
      if (!other.getClusterHostname().isEmpty()) {
        clusterHostname_ = other.clusterHostname_;
        onChanged();
      }
      if (!other.getClusterUsername().isEmpty()) {
        clusterUsername_ = other.clusterUsername_;
        onChanged();
      }
      if (!other.getClusterPassword().isEmpty()) {
        clusterPassword_ = other.clusterPassword_;
        onChanged();
      }
      if (!other.getBucketName().isEmpty()) {
        bucketName_ = other.bucketName_;
        onChanged();
      }
      if (other.getUseAsDefaultConnection() != false) {
        setUseAsDefaultConnection(other.getUseAsDefaultConnection());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.couchbase.grpc.sdk.protocol.CreateConnectionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.couchbase.grpc.sdk.protocol.CreateConnectionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object clusterHostname_ = "";
    /**
     * <code>string clusterHostname = 1;</code>
     * @return The clusterHostname.
     */
    public java.lang.String getClusterHostname() {
      java.lang.Object ref = clusterHostname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clusterHostname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clusterHostname = 1;</code>
     * @return The bytes for clusterHostname.
     */
    public com.google.protobuf.ByteString
        getClusterHostnameBytes() {
      java.lang.Object ref = clusterHostname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusterHostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clusterHostname = 1;</code>
     * @param value The clusterHostname to set.
     * @return This builder for chaining.
     */
    public Builder setClusterHostname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clusterHostname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clusterHostname = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClusterHostname() {
      
      clusterHostname_ = getDefaultInstance().getClusterHostname();
      onChanged();
      return this;
    }
    /**
     * <code>string clusterHostname = 1;</code>
     * @param value The bytes for clusterHostname to set.
     * @return This builder for chaining.
     */
    public Builder setClusterHostnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clusterHostname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object clusterUsername_ = "";
    /**
     * <code>string clusterUsername = 2;</code>
     * @return The clusterUsername.
     */
    public java.lang.String getClusterUsername() {
      java.lang.Object ref = clusterUsername_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clusterUsername_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clusterUsername = 2;</code>
     * @return The bytes for clusterUsername.
     */
    public com.google.protobuf.ByteString
        getClusterUsernameBytes() {
      java.lang.Object ref = clusterUsername_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusterUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clusterUsername = 2;</code>
     * @param value The clusterUsername to set.
     * @return This builder for chaining.
     */
    public Builder setClusterUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clusterUsername_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clusterUsername = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClusterUsername() {
      
      clusterUsername_ = getDefaultInstance().getClusterUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string clusterUsername = 2;</code>
     * @param value The bytes for clusterUsername to set.
     * @return This builder for chaining.
     */
    public Builder setClusterUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clusterUsername_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object clusterPassword_ = "";
    /**
     * <code>string clusterPassword = 3;</code>
     * @return The clusterPassword.
     */
    public java.lang.String getClusterPassword() {
      java.lang.Object ref = clusterPassword_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clusterPassword_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clusterPassword = 3;</code>
     * @return The bytes for clusterPassword.
     */
    public com.google.protobuf.ByteString
        getClusterPasswordBytes() {
      java.lang.Object ref = clusterPassword_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusterPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clusterPassword = 3;</code>
     * @param value The clusterPassword to set.
     * @return This builder for chaining.
     */
    public Builder setClusterPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clusterPassword_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clusterPassword = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearClusterPassword() {
      
      clusterPassword_ = getDefaultInstance().getClusterPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string clusterPassword = 3;</code>
     * @param value The bytes for clusterPassword to set.
     * @return This builder for chaining.
     */
    public Builder setClusterPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clusterPassword_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bucketName_ = "";
    /**
     * <code>string bucketName = 4;</code>
     * @return The bucketName.
     */
    public java.lang.String getBucketName() {
      java.lang.Object ref = bucketName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bucketName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bucketName = 4;</code>
     * @return The bytes for bucketName.
     */
    public com.google.protobuf.ByteString
        getBucketNameBytes() {
      java.lang.Object ref = bucketName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bucketName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bucketName = 4;</code>
     * @param value The bucketName to set.
     * @return This builder for chaining.
     */
    public Builder setBucketName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bucketName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bucketName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBucketName() {
      
      bucketName_ = getDefaultInstance().getBucketName();
      onChanged();
      return this;
    }
    /**
     * <code>string bucketName = 4;</code>
     * @param value The bytes for bucketName to set.
     * @return This builder for chaining.
     */
    public Builder setBucketNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bucketName_ = value;
      onChanged();
      return this;
    }

    private boolean useAsDefaultConnection_ ;
    /**
     * <code>bool useAsDefaultConnection = 5;</code>
     * @return The useAsDefaultConnection.
     */
    @java.lang.Override
    public boolean getUseAsDefaultConnection() {
      return useAsDefaultConnection_;
    }
    /**
     * <code>bool useAsDefaultConnection = 5;</code>
     * @param value The useAsDefaultConnection to set.
     * @return This builder for chaining.
     */
    public Builder setUseAsDefaultConnection(boolean value) {
      
      useAsDefaultConnection_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool useAsDefaultConnection = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUseAsDefaultConnection() {
      
      useAsDefaultConnection_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.CreateConnectionRequest)
  }

  // @@protoc_insertion_point(class_scope:protocol.CreateConnectionRequest)
  private static final com.couchbase.grpc.sdk.protocol.CreateConnectionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.couchbase.grpc.sdk.protocol.CreateConnectionRequest();
  }

  public static com.couchbase.grpc.sdk.protocol.CreateConnectionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateConnectionRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateConnectionRequest>() {
    @java.lang.Override
    public CreateConnectionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateConnectionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateConnectionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateConnectionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.couchbase.grpc.sdk.protocol.CreateConnectionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

