// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_basic.proto

package com.couchbase.grpc.sdk.protocol;

/**
 * Protobuf type {@code protocol.DocId}
 */
public final class DocId extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.DocId)
    DocIdOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DocId.newBuilder() to construct.
  private DocId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DocId() {
    bucketName_ = "";
    scopeName_ = "";
    collectionName_ = "";
    docId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DocId();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DocId(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            bucketName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            scopeName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            collectionName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            docId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SdkBasic.internal_static_protocol_DocId_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SdkBasic.internal_static_protocol_DocId_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DocId.class, DocId.Builder.class);
  }

  public static final int BUCKETNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object bucketName_;
  /**
   * <code>string bucketName = 1;</code>
   * @return The bucketName.
   */
  @java.lang.Override
  public java.lang.String getBucketName() {
    java.lang.Object ref = bucketName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bucketName_ = s;
      return s;
    }
  }
  /**
   * <code>string bucketName = 1;</code>
   * @return The bytes for bucketName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBucketNameBytes() {
    java.lang.Object ref = bucketName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bucketName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCOPENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object scopeName_;
  /**
   * <code>string scopeName = 2;</code>
   * @return The scopeName.
   */
  @java.lang.Override
  public java.lang.String getScopeName() {
    java.lang.Object ref = scopeName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scopeName_ = s;
      return s;
    }
  }
  /**
   * <code>string scopeName = 2;</code>
   * @return The bytes for scopeName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScopeNameBytes() {
    java.lang.Object ref = scopeName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scopeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLLECTIONNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object collectionName_;
  /**
   * <code>string collectionName = 3;</code>
   * @return The collectionName.
   */
  @java.lang.Override
  public java.lang.String getCollectionName() {
    java.lang.Object ref = collectionName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      collectionName_ = s;
      return s;
    }
  }
  /**
   * <code>string collectionName = 3;</code>
   * @return The bytes for collectionName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCollectionNameBytes() {
    java.lang.Object ref = collectionName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      collectionName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOCID_FIELD_NUMBER = 4;
  private volatile java.lang.Object docId_;
  /**
   * <pre>
   * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
   * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
   * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
   * </pre>
   *
   * <code>string docId = 4;</code>
   * @return The docId.
   */
  @java.lang.Override
  public java.lang.String getDocId() {
    java.lang.Object ref = docId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      docId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
   * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
   * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
   * </pre>
   *
   * <code>string docId = 4;</code>
   * @return The bytes for docId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDocIdBytes() {
    java.lang.Object ref = docId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      docId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBucketNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bucketName_);
    }
    if (!getScopeNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, scopeName_);
    }
    if (!getCollectionNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, collectionName_);
    }
    if (!getDocIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, docId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBucketNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bucketName_);
    }
    if (!getScopeNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, scopeName_);
    }
    if (!getCollectionNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, collectionName_);
    }
    if (!getDocIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, docId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DocId)) {
      return super.equals(obj);
    }
    DocId other = (DocId) obj;

    if (!getBucketName()
        .equals(other.getBucketName())) return false;
    if (!getScopeName()
        .equals(other.getScopeName())) return false;
    if (!getCollectionName()
        .equals(other.getCollectionName())) return false;
    if (!getDocId()
        .equals(other.getDocId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BUCKETNAME_FIELD_NUMBER;
    hash = (53 * hash) + getBucketName().hashCode();
    hash = (37 * hash) + SCOPENAME_FIELD_NUMBER;
    hash = (53 * hash) + getScopeName().hashCode();
    hash = (37 * hash) + COLLECTIONNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCollectionName().hashCode();
    hash = (37 * hash) + DOCID_FIELD_NUMBER;
    hash = (53 * hash) + getDocId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DocId parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DocId parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DocId parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DocId parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DocId parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DocId parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DocId parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DocId parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DocId parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DocId parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DocId parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DocId parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DocId prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.DocId}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.DocId)
          DocIdOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SdkBasic.internal_static_protocol_DocId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SdkBasic.internal_static_protocol_DocId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DocId.class, DocId.Builder.class);
    }

    // Construct using com.couchbase.grpc.sdk.protocol.DocId.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bucketName_ = "";

      scopeName_ = "";

      collectionName_ = "";

      docId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SdkBasic.internal_static_protocol_DocId_descriptor;
    }

    @java.lang.Override
    public DocId getDefaultInstanceForType() {
      return DocId.getDefaultInstance();
    }

    @java.lang.Override
    public DocId build() {
      DocId result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public DocId buildPartial() {
      DocId result = new DocId(this);
      result.bucketName_ = bucketName_;
      result.scopeName_ = scopeName_;
      result.collectionName_ = collectionName_;
      result.docId_ = docId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DocId) {
        return mergeFrom((DocId)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DocId other) {
      if (other == DocId.getDefaultInstance()) return this;
      if (!other.getBucketName().isEmpty()) {
        bucketName_ = other.bucketName_;
        onChanged();
      }
      if (!other.getScopeName().isEmpty()) {
        scopeName_ = other.scopeName_;
        onChanged();
      }
      if (!other.getCollectionName().isEmpty()) {
        collectionName_ = other.collectionName_;
        onChanged();
      }
      if (!other.getDocId().isEmpty()) {
        docId_ = other.docId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DocId parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DocId) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object bucketName_ = "";
    /**
     * <code>string bucketName = 1;</code>
     * @return The bucketName.
     */
    public java.lang.String getBucketName() {
      java.lang.Object ref = bucketName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bucketName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bucketName = 1;</code>
     * @return The bytes for bucketName.
     */
    public com.google.protobuf.ByteString
        getBucketNameBytes() {
      java.lang.Object ref = bucketName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bucketName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bucketName = 1;</code>
     * @param value The bucketName to set.
     * @return This builder for chaining.
     */
    public Builder setBucketName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bucketName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bucketName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBucketName() {
      
      bucketName_ = getDefaultInstance().getBucketName();
      onChanged();
      return this;
    }
    /**
     * <code>string bucketName = 1;</code>
     * @param value The bytes for bucketName to set.
     * @return This builder for chaining.
     */
    public Builder setBucketNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bucketName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object scopeName_ = "";
    /**
     * <code>string scopeName = 2;</code>
     * @return The scopeName.
     */
    public java.lang.String getScopeName() {
      java.lang.Object ref = scopeName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scopeName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string scopeName = 2;</code>
     * @return The bytes for scopeName.
     */
    public com.google.protobuf.ByteString
        getScopeNameBytes() {
      java.lang.Object ref = scopeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scopeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string scopeName = 2;</code>
     * @param value The scopeName to set.
     * @return This builder for chaining.
     */
    public Builder setScopeName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      scopeName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string scopeName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearScopeName() {
      
      scopeName_ = getDefaultInstance().getScopeName();
      onChanged();
      return this;
    }
    /**
     * <code>string scopeName = 2;</code>
     * @param value The bytes for scopeName to set.
     * @return This builder for chaining.
     */
    public Builder setScopeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      scopeName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object collectionName_ = "";
    /**
     * <code>string collectionName = 3;</code>
     * @return The collectionName.
     */
    public java.lang.String getCollectionName() {
      java.lang.Object ref = collectionName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        collectionName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string collectionName = 3;</code>
     * @return The bytes for collectionName.
     */
    public com.google.protobuf.ByteString
        getCollectionNameBytes() {
      java.lang.Object ref = collectionName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collectionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string collectionName = 3;</code>
     * @param value The collectionName to set.
     * @return This builder for chaining.
     */
    public Builder setCollectionName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      collectionName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string collectionName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCollectionName() {
      
      collectionName_ = getDefaultInstance().getCollectionName();
      onChanged();
      return this;
    }
    /**
     * <code>string collectionName = 3;</code>
     * @param value The bytes for collectionName to set.
     * @return This builder for chaining.
     */
    public Builder setCollectionNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      collectionName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object docId_ = "";
    /**
     * <pre>
     * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
     * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
     * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
     * </pre>
     *
     * <code>string docId = 4;</code>
     * @return The docId.
     */
    public java.lang.String getDocId() {
      java.lang.Object ref = docId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        docId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
     * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
     * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
     * </pre>
     *
     * <code>string docId = 4;</code>
     * @return The bytes for docId.
     */
    public com.google.protobuf.ByteString
        getDocIdBytes() {
      java.lang.Object ref = docId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        docId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
     * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
     * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
     * </pre>
     *
     * <code>string docId = 4;</code>
     * @param value The docId to set.
     * @return This builder for chaining.
     */
    public Builder setDocId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      docId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
     * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
     * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
     * </pre>
     *
     * <code>string docId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDocId() {
      
      docId_ = getDefaultInstance().getDocId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PERF_PERFORMER: this can start with "__doc_X", in which case a UUID for XXX should be generated or used automatically by
     * the performer.  E.g. the first use of "__doc_0" in a transaction should create a new UUID for 0, and then subsequent uses
     * of "__doc_0" in the same transaction should reuse that UUID.  X will always be an integer.
     * </pre>
     *
     * <code>string docId = 4;</code>
     * @param value The bytes for docId to set.
     * @return This builder for chaining.
     */
    public Builder setDocIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      docId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.DocId)
  }

  // @@protoc_insertion_point(class_scope:protocol.DocId)
  private static final DocId DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DocId();
  }

  public static DocId getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DocId>
      PARSER = new com.google.protobuf.AbstractParser<DocId>() {
    @java.lang.Override
    public DocId parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DocId(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DocId> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DocId> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public DocId getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

