// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_commands.proto

package com.couchbase.grpc.sdk.protocol;

/**
 * Protobuf enum {@code protocol.ExternalException}
 */
public enum ExternalException
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Unknown = 0;</code>
   */
  Unknown(0),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Unknown = 0;</code>
   */
  public static final int Unknown_VALUE = 0;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ExternalException valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ExternalException forNumber(int value) {
    switch (value) {
      case 0: return Unknown;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ExternalException>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ExternalException> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ExternalException>() {
          public ExternalException findValueByNumber(int number) {
            return ExternalException.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.couchbase.grpc.sdk.protocol.SdkCommands.getDescriptor().getEnumTypes().get(1);
  }

  private static final ExternalException[] VALUES = values();

  public static ExternalException valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ExternalException(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:protocol.ExternalException)
}

