// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_performer.proto

package com.couchbase.grpc.sdk.protocol;

/**
 * Protobuf type {@code protocol.PerfRunRequest}
 */
public final class PerfRunRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.PerfRunRequest)
    PerfRunRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PerfRunRequest.newBuilder() to construct.
  private PerfRunRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PerfRunRequest() {
    clusterConnectionId_ = "";
    horizontalScaling_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PerfRunRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PerfRunRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            clusterConnectionId_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              horizontalScaling_ = new java.util.ArrayList<PerfRunHorizontalScaling>();
              mutable_bitField0_ |= 0x00000001;
            }
            horizontalScaling_.add(
                input.readMessage(PerfRunHorizontalScaling.parser(), extensionRegistry));
            break;
          }
          case 32: {

            runForSeconds_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        horizontalScaling_ = java.util.Collections.unmodifiableList(horizontalScaling_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SdkPerformer.internal_static_protocol_PerfRunRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SdkPerformer.internal_static_protocol_PerfRunRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PerfRunRequest.class, PerfRunRequest.Builder.class);
  }

  public static final int CLUSTERCONNECTIONID_FIELD_NUMBER = 1;
  private volatile java.lang.Object clusterConnectionId_;
  /**
   * <pre>
   * Optional, allows a custom Cluster connection to be used
   * </pre>
   *
   * <code>string clusterConnectionId = 1;</code>
   * @return The clusterConnectionId.
   */
  @java.lang.Override
  public java.lang.String getClusterConnectionId() {
    java.lang.Object ref = clusterConnectionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clusterConnectionId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional, allows a custom Cluster connection to be used
   * </pre>
   *
   * <code>string clusterConnectionId = 1;</code>
   * @return The bytes for clusterConnectionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClusterConnectionIdBytes() {
    java.lang.Object ref = clusterConnectionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clusterConnectionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HORIZONTALSCALING_FIELD_NUMBER = 2;
  private java.util.List<PerfRunHorizontalScaling> horizontalScaling_;
  /**
   * <pre>
   * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
   * required.
   * </pre>
   *
   * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
   */
  @java.lang.Override
  public java.util.List<PerfRunHorizontalScaling> getHorizontalScalingList() {
    return horizontalScaling_;
  }
  /**
   * <pre>
   * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
   * required.
   * </pre>
   *
   * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends PerfRunHorizontalScalingOrBuilder>
      getHorizontalScalingOrBuilderList() {
    return horizontalScaling_;
  }
  /**
   * <pre>
   * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
   * required.
   * </pre>
   *
   * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
   */
  @java.lang.Override
  public int getHorizontalScalingCount() {
    return horizontalScaling_.size();
  }
  /**
   * <pre>
   * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
   * required.
   * </pre>
   *
   * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
   */
  @java.lang.Override
  public PerfRunHorizontalScaling getHorizontalScaling(int index) {
    return horizontalScaling_.get(index);
  }
  /**
   * <pre>
   * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
   * required.
   * </pre>
   *
   * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
   */
  @java.lang.Override
  public PerfRunHorizontalScalingOrBuilder getHorizontalScalingOrBuilder(
      int index) {
    return horizontalScaling_.get(index);
  }

  public static final int RUNFORSECONDS_FIELD_NUMBER = 4;
  private int runForSeconds_;
  /**
   * <pre>
   * Performer will run until this much time has elapsed.
   * Counted from when it creates the factory, after waiting for the bucket to be opened.
   * </pre>
   *
   * <code>int32 runForSeconds = 4;</code>
   * @return The runForSeconds.
   */
  @java.lang.Override
  public int getRunForSeconds() {
    return runForSeconds_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClusterConnectionIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clusterConnectionId_);
    }
    for (int i = 0; i < horizontalScaling_.size(); i++) {
      output.writeMessage(2, horizontalScaling_.get(i));
    }
    if (runForSeconds_ != 0) {
      output.writeInt32(4, runForSeconds_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClusterConnectionIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clusterConnectionId_);
    }
    for (int i = 0; i < horizontalScaling_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, horizontalScaling_.get(i));
    }
    if (runForSeconds_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, runForSeconds_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PerfRunRequest)) {
      return super.equals(obj);
    }
    PerfRunRequest other = (PerfRunRequest) obj;

    if (!getClusterConnectionId()
        .equals(other.getClusterConnectionId())) return false;
    if (!getHorizontalScalingList()
        .equals(other.getHorizontalScalingList())) return false;
    if (getRunForSeconds()
        != other.getRunForSeconds()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLUSTERCONNECTIONID_FIELD_NUMBER;
    hash = (53 * hash) + getClusterConnectionId().hashCode();
    if (getHorizontalScalingCount() > 0) {
      hash = (37 * hash) + HORIZONTALSCALING_FIELD_NUMBER;
      hash = (53 * hash) + getHorizontalScalingList().hashCode();
    }
    hash = (37 * hash) + RUNFORSECONDS_FIELD_NUMBER;
    hash = (53 * hash) + getRunForSeconds();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PerfRunRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PerfRunRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PerfRunRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PerfRunRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PerfRunRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PerfRunRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PerfRunRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PerfRunRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static PerfRunRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static PerfRunRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PerfRunRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PerfRunRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PerfRunRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.PerfRunRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.PerfRunRequest)
          PerfRunRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SdkPerformer.internal_static_protocol_PerfRunRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SdkPerformer.internal_static_protocol_PerfRunRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PerfRunRequest.class, PerfRunRequest.Builder.class);
    }

    // Construct using com.couchbase.grpc.sdk.protocol.PerfRunRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHorizontalScalingFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clusterConnectionId_ = "";

      if (horizontalScalingBuilder_ == null) {
        horizontalScaling_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        horizontalScalingBuilder_.clear();
      }
      runForSeconds_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SdkPerformer.internal_static_protocol_PerfRunRequest_descriptor;
    }

    @java.lang.Override
    public PerfRunRequest getDefaultInstanceForType() {
      return PerfRunRequest.getDefaultInstance();
    }

    @java.lang.Override
    public PerfRunRequest build() {
      PerfRunRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public PerfRunRequest buildPartial() {
      PerfRunRequest result = new PerfRunRequest(this);
      int from_bitField0_ = bitField0_;
      result.clusterConnectionId_ = clusterConnectionId_;
      if (horizontalScalingBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          horizontalScaling_ = java.util.Collections.unmodifiableList(horizontalScaling_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.horizontalScaling_ = horizontalScaling_;
      } else {
        result.horizontalScaling_ = horizontalScalingBuilder_.build();
      }
      result.runForSeconds_ = runForSeconds_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PerfRunRequest) {
        return mergeFrom((PerfRunRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PerfRunRequest other) {
      if (other == PerfRunRequest.getDefaultInstance()) return this;
      if (!other.getClusterConnectionId().isEmpty()) {
        clusterConnectionId_ = other.clusterConnectionId_;
        onChanged();
      }
      if (horizontalScalingBuilder_ == null) {
        if (!other.horizontalScaling_.isEmpty()) {
          if (horizontalScaling_.isEmpty()) {
            horizontalScaling_ = other.horizontalScaling_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHorizontalScalingIsMutable();
            horizontalScaling_.addAll(other.horizontalScaling_);
          }
          onChanged();
        }
      } else {
        if (!other.horizontalScaling_.isEmpty()) {
          if (horizontalScalingBuilder_.isEmpty()) {
            horizontalScalingBuilder_.dispose();
            horizontalScalingBuilder_ = null;
            horizontalScaling_ = other.horizontalScaling_;
            bitField0_ = (bitField0_ & ~0x00000001);
            horizontalScalingBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHorizontalScalingFieldBuilder() : null;
          } else {
            horizontalScalingBuilder_.addAllMessages(other.horizontalScaling_);
          }
        }
      }
      if (other.getRunForSeconds() != 0) {
        setRunForSeconds(other.getRunForSeconds());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      PerfRunRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (PerfRunRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object clusterConnectionId_ = "";
    /**
     * <pre>
     * Optional, allows a custom Cluster connection to be used
     * </pre>
     *
     * <code>string clusterConnectionId = 1;</code>
     * @return The clusterConnectionId.
     */
    public java.lang.String getClusterConnectionId() {
      java.lang.Object ref = clusterConnectionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clusterConnectionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional, allows a custom Cluster connection to be used
     * </pre>
     *
     * <code>string clusterConnectionId = 1;</code>
     * @return The bytes for clusterConnectionId.
     */
    public com.google.protobuf.ByteString
        getClusterConnectionIdBytes() {
      java.lang.Object ref = clusterConnectionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusterConnectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional, allows a custom Cluster connection to be used
     * </pre>
     *
     * <code>string clusterConnectionId = 1;</code>
     * @param value The clusterConnectionId to set.
     * @return This builder for chaining.
     */
    public Builder setClusterConnectionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clusterConnectionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional, allows a custom Cluster connection to be used
     * </pre>
     *
     * <code>string clusterConnectionId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClusterConnectionId() {
      
      clusterConnectionId_ = getDefaultInstance().getClusterConnectionId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional, allows a custom Cluster connection to be used
     * </pre>
     *
     * <code>string clusterConnectionId = 1;</code>
     * @param value The bytes for clusterConnectionId to set.
     * @return This builder for chaining.
     */
    public Builder setClusterConnectionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clusterConnectionId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<PerfRunHorizontalScaling> horizontalScaling_ =
      java.util.Collections.emptyList();
    private void ensureHorizontalScalingIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        horizontalScaling_ = new java.util.ArrayList<PerfRunHorizontalScaling>(horizontalScaling_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            PerfRunHorizontalScaling, PerfRunHorizontalScaling.Builder, PerfRunHorizontalScalingOrBuilder> horizontalScalingBuilder_;

    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public java.util.List<PerfRunHorizontalScaling> getHorizontalScalingList() {
      if (horizontalScalingBuilder_ == null) {
        return java.util.Collections.unmodifiableList(horizontalScaling_);
      } else {
        return horizontalScalingBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public int getHorizontalScalingCount() {
      if (horizontalScalingBuilder_ == null) {
        return horizontalScaling_.size();
      } else {
        return horizontalScalingBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public PerfRunHorizontalScaling getHorizontalScaling(int index) {
      if (horizontalScalingBuilder_ == null) {
        return horizontalScaling_.get(index);
      } else {
        return horizontalScalingBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public Builder setHorizontalScaling(
        int index, PerfRunHorizontalScaling value) {
      if (horizontalScalingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHorizontalScalingIsMutable();
        horizontalScaling_.set(index, value);
        onChanged();
      } else {
        horizontalScalingBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public Builder setHorizontalScaling(
        int index, PerfRunHorizontalScaling.Builder builderForValue) {
      if (horizontalScalingBuilder_ == null) {
        ensureHorizontalScalingIsMutable();
        horizontalScaling_.set(index, builderForValue.build());
        onChanged();
      } else {
        horizontalScalingBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public Builder addHorizontalScaling(PerfRunHorizontalScaling value) {
      if (horizontalScalingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHorizontalScalingIsMutable();
        horizontalScaling_.add(value);
        onChanged();
      } else {
        horizontalScalingBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public Builder addHorizontalScaling(
        int index, PerfRunHorizontalScaling value) {
      if (horizontalScalingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHorizontalScalingIsMutable();
        horizontalScaling_.add(index, value);
        onChanged();
      } else {
        horizontalScalingBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public Builder addHorizontalScaling(
        PerfRunHorizontalScaling.Builder builderForValue) {
      if (horizontalScalingBuilder_ == null) {
        ensureHorizontalScalingIsMutable();
        horizontalScaling_.add(builderForValue.build());
        onChanged();
      } else {
        horizontalScalingBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public Builder addHorizontalScaling(
        int index, PerfRunHorizontalScaling.Builder builderForValue) {
      if (horizontalScalingBuilder_ == null) {
        ensureHorizontalScalingIsMutable();
        horizontalScaling_.add(index, builderForValue.build());
        onChanged();
      } else {
        horizontalScalingBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public Builder addAllHorizontalScaling(
        java.lang.Iterable<? extends PerfRunHorizontalScaling> values) {
      if (horizontalScalingBuilder_ == null) {
        ensureHorizontalScalingIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, horizontalScaling_);
        onChanged();
      } else {
        horizontalScalingBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public Builder clearHorizontalScaling() {
      if (horizontalScalingBuilder_ == null) {
        horizontalScaling_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        horizontalScalingBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public Builder removeHorizontalScaling(int index) {
      if (horizontalScalingBuilder_ == null) {
        ensureHorizontalScalingIsMutable();
        horizontalScaling_.remove(index);
        onChanged();
      } else {
        horizontalScalingBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public PerfRunHorizontalScaling.Builder getHorizontalScalingBuilder(
        int index) {
      return getHorizontalScalingFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public PerfRunHorizontalScalingOrBuilder getHorizontalScalingOrBuilder(
        int index) {
      if (horizontalScalingBuilder_ == null) {
        return horizontalScaling_.get(index);  } else {
        return horizontalScalingBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public java.util.List<? extends PerfRunHorizontalScalingOrBuilder>
         getHorizontalScalingOrBuilderList() {
      if (horizontalScalingBuilder_ != null) {
        return horizontalScalingBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(horizontalScaling_);
      }
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public PerfRunHorizontalScaling.Builder addHorizontalScalingBuilder() {
      return getHorizontalScalingFieldBuilder().addBuilder(
          PerfRunHorizontalScaling.getDefaultInstance());
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public PerfRunHorizontalScaling.Builder addHorizontalScalingBuilder(
        int index) {
      return getHorizontalScalingFieldBuilder().addBuilder(
          index, PerfRunHorizontalScaling.getDefaultInstance());
    }
    /**
     * <pre>
     * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
     * required.
     * </pre>
     *
     * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
     */
    public java.util.List<PerfRunHorizontalScaling.Builder>
         getHorizontalScalingBuilderList() {
      return getHorizontalScalingFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            PerfRunHorizontalScaling, PerfRunHorizontalScaling.Builder, PerfRunHorizontalScalingOrBuilder>
        getHorizontalScalingFieldBuilder() {
      if (horizontalScalingBuilder_ == null) {
        horizontalScalingBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                PerfRunHorizontalScaling, PerfRunHorizontalScaling.Builder, PerfRunHorizontalScalingOrBuilder>(
                horizontalScaling_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        horizontalScaling_ = null;
      }
      return horizontalScalingBuilder_;
    }

    private int runForSeconds_ ;
    /**
     * <pre>
     * Performer will run until this much time has elapsed.
     * Counted from when it creates the factory, after waiting for the bucket to be opened.
     * </pre>
     *
     * <code>int32 runForSeconds = 4;</code>
     * @return The runForSeconds.
     */
    @java.lang.Override
    public int getRunForSeconds() {
      return runForSeconds_;
    }
    /**
     * <pre>
     * Performer will run until this much time has elapsed.
     * Counted from when it creates the factory, after waiting for the bucket to be opened.
     * </pre>
     *
     * <code>int32 runForSeconds = 4;</code>
     * @param value The runForSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setRunForSeconds(int value) {
      
      runForSeconds_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Performer will run until this much time has elapsed.
     * Counted from when it creates the factory, after waiting for the bucket to be opened.
     * </pre>
     *
     * <code>int32 runForSeconds = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRunForSeconds() {
      
      runForSeconds_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.PerfRunRequest)
  }

  // @@protoc_insertion_point(class_scope:protocol.PerfRunRequest)
  private static final PerfRunRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PerfRunRequest();
  }

  public static PerfRunRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PerfRunRequest>
      PARSER = new com.google.protobuf.AbstractParser<PerfRunRequest>() {
    @java.lang.Override
    public PerfRunRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PerfRunRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PerfRunRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PerfRunRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public PerfRunRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

