// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_performer.proto

package com.couchbase.grpc.sdk.protocol;

public interface PerfRunHorizontalScalingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.PerfRunHorizontalScaling)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Performer will run these transactions, in a loop.
   * </pre>
   *
   * <code>repeated .protocol.SdkCreateRequest sdkCommand = 1;</code>
   */
  java.util.List<com.couchbase.grpc.sdk.protocol.SdkCreateRequest> 
      getSdkCommandList();
  /**
   * <pre>
   * Performer will run these transactions, in a loop.
   * </pre>
   *
   * <code>repeated .protocol.SdkCreateRequest sdkCommand = 1;</code>
   */
  com.couchbase.grpc.sdk.protocol.SdkCreateRequest getSdkCommand(int index);
  /**
   * <pre>
   * Performer will run these transactions, in a loop.
   * </pre>
   *
   * <code>repeated .protocol.SdkCreateRequest sdkCommand = 1;</code>
   */
  int getSdkCommandCount();
  /**
   * <pre>
   * Performer will run these transactions, in a loop.
   * </pre>
   *
   * <code>repeated .protocol.SdkCreateRequest sdkCommand = 1;</code>
   */
  java.util.List<? extends com.couchbase.grpc.sdk.protocol.SdkCreateRequestOrBuilder> 
      getSdkCommandOrBuilderList();
  /**
   * <pre>
   * Performer will run these transactions, in a loop.
   * </pre>
   *
   * <code>repeated .protocol.SdkCreateRequest sdkCommand = 1;</code>
   */
  com.couchbase.grpc.sdk.protocol.SdkCreateRequestOrBuilder getSdkCommandOrBuilder(
      int index);
}
