// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_performer.proto

package com.couchbase.grpc.sdk.protocol;

public interface PerfSingleSdkOpResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.PerfSingleSdkOpResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Implementations should not provide the logs field here, to conserve memory &amp; bandwidth
   * </pre>
   *
   * <code>.protocol.SdkCommandResult results = 1;</code>
   * @return Whether the results field is set.
   */
  boolean hasResults();
  /**
   * <pre>
   * Implementations should not provide the logs field here, to conserve memory &amp; bandwidth
   * </pre>
   *
   * <code>.protocol.SdkCommandResult results = 1;</code>
   * @return The results.
   */
  com.couchbase.grpc.sdk.protocol.SdkCommandResult getResults();
  /**
   * <pre>
   * Implementations should not provide the logs field here, to conserve memory &amp; bandwidth
   * </pre>
   *
   * <code>.protocol.SdkCommandResult results = 1;</code>
   */
  com.couchbase.grpc.sdk.protocol.SdkCommandResultOrBuilder getResultsOrBuilder();

  /**
   * <code>string versionId = 2;</code>
   * @return The versionId.
   */
  java.lang.String getVersionId();
  /**
   * <code>string versionId = 2;</code>
   * @return The bytes for versionId.
   */
  com.google.protobuf.ByteString
      getVersionIdBytes();

  /**
   * <code>.google.protobuf.Timestamp initiated = 3;</code>
   * @return Whether the initiated field is set.
   */
  boolean hasInitiated();
  /**
   * <code>.google.protobuf.Timestamp initiated = 3;</code>
   * @return The initiated.
   */
  com.google.protobuf.Timestamp getInitiated();
  /**
   * <code>.google.protobuf.Timestamp initiated = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getInitiatedOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp finished = 4;</code>
   * @return Whether the finished field is set.
   */
  boolean hasFinished();
  /**
   * <code>.google.protobuf.Timestamp finished = 4;</code>
   * @return The finished.
   */
  com.google.protobuf.Timestamp getFinished();
  /**
   * <code>.google.protobuf.Timestamp finished = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getFinishedOrBuilder();
}
