// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_performer.proto

package com.couchbase.grpc.sdk.protocol;

public interface PerfRunRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.PerfRunRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional, allows a custom Cluster connection to be used
   * </pre>
   *
   * <code>string clusterConnectionId = 1;</code>
   * @return The clusterConnectionId.
   */
  java.lang.String getClusterConnectionId();
  /**
   * <pre>
   * Optional, allows a custom Cluster connection to be used
   * </pre>
   *
   * <code>string clusterConnectionId = 1;</code>
   * @return The bytes for clusterConnectionId.
   */
  com.google.protobuf.ByteString
      getClusterConnectionIdBytes();

  /**
   * <pre>
   * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
   * required.
   * </pre>
   *
   * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
   */
  java.util.List<com.couchbase.grpc.sdk.protocol.PerfRunHorizontalScaling> 
      getHorizontalScalingList();
  /**
   * <pre>
   * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
   * required.
   * </pre>
   *
   * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
   */
  com.couchbase.grpc.sdk.protocol.PerfRunHorizontalScaling getHorizontalScaling(int index);
  /**
   * <pre>
   * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
   * required.
   * </pre>
   *
   * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
   */
  int getHorizontalScalingCount();
  /**
   * <pre>
   * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
   * required.
   * </pre>
   *
   * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
   */
  java.util.List<? extends com.couchbase.grpc.sdk.protocol.PerfRunHorizontalScalingOrBuilder> 
      getHorizontalScalingOrBuilderList();
  /**
   * <pre>
   * See PerfRunHorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent transactions
   * required.
   * </pre>
   *
   * <code>repeated .protocol.PerfRunHorizontalScaling horizontalScaling = 2;</code>
   */
  com.couchbase.grpc.sdk.protocol.PerfRunHorizontalScalingOrBuilder getHorizontalScalingOrBuilder(
      int index);

  /**
   * <pre>
   * Performer will run until this much time has elapsed.
   * Counted from when it creates the factory, after waiting for the bucket to be opened.
   * </pre>
   *
   * <code>int32 runForSeconds = 3;</code>
   * @return The runForSeconds.
   */
  int getRunForSeconds();
}
