// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_commands.proto

package com.couchbase.grpc.sdk.protocol;

public final class SdkCommands {
  private SdkCommands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_CommandInsert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_CommandInsert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_SdkCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_SdkCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022sdk_commands.proto\022\010protocol\032\017sdk_basi" +
      "c.proto\"D\n\rCommandInsert\022\036\n\005docId\030\001 \001(\0132" +
      "\017.protocol.DocId\022\023\n\013contentJson\030\002 \001(\t\"B\n" +
      "\nSdkCommand\022)\n\006insert\030\001 \001(\0132\027.protocol.C" +
      "ommandInsertH\000B\t\n\007command*M\n\014SdkExceptio" +
      "n\022\027\n\023NO_EXCEPTION_THROWN\020\000\022\r\n\tEXCEPTION\020" +
      "\001\022\025\n\021EXCEPTION_UNKNOWN\020\002* \n\021ExternalExce" +
      "ption\022\013\n\007Unknown\020\000B{\n\037com.couchbase.grpc" +
      ".sdk.protocolP\001Z<github.com/couchbaselab" +
      "s/transactions-fit-performer/protocol\252\002\027" +
      "Couchbase.Grpc.Protocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SdkBasic.getDescriptor(),
        });
    internal_static_protocol_CommandInsert_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_CommandInsert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_CommandInsert_descriptor,
        new java.lang.String[] { "DocId", "ContentJson", });
    internal_static_protocol_SdkCommand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_SdkCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_SdkCommand_descriptor,
        new java.lang.String[] { "Insert", "Command", });
    SdkBasic.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
