// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_performer.proto

package com.couchbase.grpc.sdk.protocol;

/**
 * Protobuf type {@code protocol.SdkCreateRequest}
 */
public final class SdkCreateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.SdkCreateRequest)
    SdkCreateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SdkCreateRequest.newBuilder() to construct.
  private SdkCreateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SdkCreateRequest() {
    attempts_ = java.util.Collections.emptyList();
    name_ = "";
    clusterConnectionId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SdkCreateRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SdkCreateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              attempts_ = new java.util.ArrayList<SdkAttemptRequest>();
              mutable_bitField0_ |= 0x00000001;
            }
            attempts_.add(
                input.readMessage(SdkAttemptRequest.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            clusterConnectionId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        attempts_ = java.util.Collections.unmodifiableList(attempts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return SdkPerformer.internal_static_protocol_SdkCreateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return SdkPerformer.internal_static_protocol_SdkCreateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SdkCreateRequest.class, SdkCreateRequest.Builder.class);
  }

  public static final int ATTEMPTS_FIELD_NUMBER = 1;
  private java.util.List<SdkAttemptRequest> attempts_;
  /**
   * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<SdkAttemptRequest> getAttemptsList() {
    return attempts_;
  }
  /**
   * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends SdkAttemptRequestOrBuilder>
      getAttemptsOrBuilderList() {
    return attempts_;
  }
  /**
   * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
   */
  @java.lang.Override
  public int getAttemptsCount() {
    return attempts_.size();
  }
  /**
   * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
   */
  @java.lang.Override
  public SdkAttemptRequest getAttempts(int index) {
    return attempts_.get(index);
  }
  /**
   * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
   */
  @java.lang.Override
  public SdkAttemptRequestOrBuilder getAttemptsOrBuilder(
      int index) {
    return attempts_.get(index);
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLUSTERCONNECTIONID_FIELD_NUMBER = 3;
  private volatile java.lang.Object clusterConnectionId_;
  /**
   * <code>string clusterConnectionId = 3;</code>
   * @return The clusterConnectionId.
   */
  @java.lang.Override
  public java.lang.String getClusterConnectionId() {
    java.lang.Object ref = clusterConnectionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clusterConnectionId_ = s;
      return s;
    }
  }
  /**
   * <code>string clusterConnectionId = 3;</code>
   * @return The bytes for clusterConnectionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClusterConnectionIdBytes() {
    java.lang.Object ref = clusterConnectionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clusterConnectionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < attempts_.size(); i++) {
      output.writeMessage(1, attempts_.get(i));
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getClusterConnectionIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clusterConnectionId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < attempts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, attempts_.get(i));
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getClusterConnectionIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clusterConnectionId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SdkCreateRequest)) {
      return super.equals(obj);
    }
    SdkCreateRequest other = (SdkCreateRequest) obj;

    if (!getAttemptsList()
        .equals(other.getAttemptsList())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getClusterConnectionId()
        .equals(other.getClusterConnectionId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAttemptsCount() > 0) {
      hash = (37 * hash) + ATTEMPTS_FIELD_NUMBER;
      hash = (53 * hash) + getAttemptsList().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CLUSTERCONNECTIONID_FIELD_NUMBER;
    hash = (53 * hash) + getClusterConnectionId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SdkCreateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SdkCreateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SdkCreateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SdkCreateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SdkCreateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SdkCreateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SdkCreateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SdkCreateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SdkCreateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SdkCreateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SdkCreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SdkCreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SdkCreateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.SdkCreateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.SdkCreateRequest)
          SdkCreateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SdkPerformer.internal_static_protocol_SdkCreateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SdkPerformer.internal_static_protocol_SdkCreateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SdkCreateRequest.class, SdkCreateRequest.Builder.class);
    }

    // Construct using com.couchbase.grpc.sdk.protocol.SdkCreateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAttemptsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (attemptsBuilder_ == null) {
        attempts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        attemptsBuilder_.clear();
      }
      name_ = "";

      clusterConnectionId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return SdkPerformer.internal_static_protocol_SdkCreateRequest_descriptor;
    }

    @java.lang.Override
    public SdkCreateRequest getDefaultInstanceForType() {
      return SdkCreateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public SdkCreateRequest build() {
      SdkCreateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public SdkCreateRequest buildPartial() {
      SdkCreateRequest result = new SdkCreateRequest(this);
      int from_bitField0_ = bitField0_;
      if (attemptsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          attempts_ = java.util.Collections.unmodifiableList(attempts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.attempts_ = attempts_;
      } else {
        result.attempts_ = attemptsBuilder_.build();
      }
      result.name_ = name_;
      result.clusterConnectionId_ = clusterConnectionId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SdkCreateRequest) {
        return mergeFrom((SdkCreateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SdkCreateRequest other) {
      if (other == SdkCreateRequest.getDefaultInstance()) return this;
      if (attemptsBuilder_ == null) {
        if (!other.attempts_.isEmpty()) {
          if (attempts_.isEmpty()) {
            attempts_ = other.attempts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAttemptsIsMutable();
            attempts_.addAll(other.attempts_);
          }
          onChanged();
        }
      } else {
        if (!other.attempts_.isEmpty()) {
          if (attemptsBuilder_.isEmpty()) {
            attemptsBuilder_.dispose();
            attemptsBuilder_ = null;
            attempts_ = other.attempts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            attemptsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAttemptsFieldBuilder() : null;
          } else {
            attemptsBuilder_.addAllMessages(other.attempts_);
          }
        }
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getClusterConnectionId().isEmpty()) {
        clusterConnectionId_ = other.clusterConnectionId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SdkCreateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SdkCreateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<SdkAttemptRequest> attempts_ =
      java.util.Collections.emptyList();
    private void ensureAttemptsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        attempts_ = new java.util.ArrayList<SdkAttemptRequest>(attempts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            SdkAttemptRequest, SdkAttemptRequest.Builder, SdkAttemptRequestOrBuilder> attemptsBuilder_;

    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public java.util.List<SdkAttemptRequest> getAttemptsList() {
      if (attemptsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(attempts_);
      } else {
        return attemptsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public int getAttemptsCount() {
      if (attemptsBuilder_ == null) {
        return attempts_.size();
      } else {
        return attemptsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public SdkAttemptRequest getAttempts(int index) {
      if (attemptsBuilder_ == null) {
        return attempts_.get(index);
      } else {
        return attemptsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public Builder setAttempts(
        int index, SdkAttemptRequest value) {
      if (attemptsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttemptsIsMutable();
        attempts_.set(index, value);
        onChanged();
      } else {
        attemptsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public Builder setAttempts(
        int index, SdkAttemptRequest.Builder builderForValue) {
      if (attemptsBuilder_ == null) {
        ensureAttemptsIsMutable();
        attempts_.set(index, builderForValue.build());
        onChanged();
      } else {
        attemptsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public Builder addAttempts(SdkAttemptRequest value) {
      if (attemptsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttemptsIsMutable();
        attempts_.add(value);
        onChanged();
      } else {
        attemptsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public Builder addAttempts(
        int index, SdkAttemptRequest value) {
      if (attemptsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttemptsIsMutable();
        attempts_.add(index, value);
        onChanged();
      } else {
        attemptsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public Builder addAttempts(
        SdkAttemptRequest.Builder builderForValue) {
      if (attemptsBuilder_ == null) {
        ensureAttemptsIsMutable();
        attempts_.add(builderForValue.build());
        onChanged();
      } else {
        attemptsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public Builder addAttempts(
        int index, SdkAttemptRequest.Builder builderForValue) {
      if (attemptsBuilder_ == null) {
        ensureAttemptsIsMutable();
        attempts_.add(index, builderForValue.build());
        onChanged();
      } else {
        attemptsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public Builder addAllAttempts(
        java.lang.Iterable<? extends SdkAttemptRequest> values) {
      if (attemptsBuilder_ == null) {
        ensureAttemptsIsMutable();
        addAll(
            values, attempts_);
        onChanged();
      } else {
        attemptsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public Builder clearAttempts() {
      if (attemptsBuilder_ == null) {
        attempts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        attemptsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public Builder removeAttempts(int index) {
      if (attemptsBuilder_ == null) {
        ensureAttemptsIsMutable();
        attempts_.remove(index);
        onChanged();
      } else {
        attemptsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public SdkAttemptRequest.Builder getAttemptsBuilder(
        int index) {
      return getAttemptsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public SdkAttemptRequestOrBuilder getAttemptsOrBuilder(
        int index) {
      if (attemptsBuilder_ == null) {
        return attempts_.get(index);  } else {
        return attemptsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public java.util.List<? extends SdkAttemptRequestOrBuilder>
         getAttemptsOrBuilderList() {
      if (attemptsBuilder_ != null) {
        return attemptsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(attempts_);
      }
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public SdkAttemptRequest.Builder addAttemptsBuilder() {
      return getAttemptsFieldBuilder().addBuilder(
          SdkAttemptRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public SdkAttemptRequest.Builder addAttemptsBuilder(
        int index) {
      return getAttemptsFieldBuilder().addBuilder(
          index, SdkAttemptRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.SdkAttemptRequest attempts = 1;</code>
     */
    public java.util.List<SdkAttemptRequest.Builder>
         getAttemptsBuilderList() {
      return getAttemptsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            SdkAttemptRequest, SdkAttemptRequest.Builder, SdkAttemptRequestOrBuilder>
        getAttemptsFieldBuilder() {
      if (attemptsBuilder_ == null) {
        attemptsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                SdkAttemptRequest, SdkAttemptRequest.Builder, SdkAttemptRequestOrBuilder>(
                attempts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        attempts_ = null;
      }
      return attemptsBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object clusterConnectionId_ = "";
    /**
     * <code>string clusterConnectionId = 3;</code>
     * @return The clusterConnectionId.
     */
    public java.lang.String getClusterConnectionId() {
      java.lang.Object ref = clusterConnectionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clusterConnectionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clusterConnectionId = 3;</code>
     * @return The bytes for clusterConnectionId.
     */
    public com.google.protobuf.ByteString
        getClusterConnectionIdBytes() {
      java.lang.Object ref = clusterConnectionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusterConnectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clusterConnectionId = 3;</code>
     * @param value The clusterConnectionId to set.
     * @return This builder for chaining.
     */
    public Builder setClusterConnectionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clusterConnectionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clusterConnectionId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearClusterConnectionId() {
      
      clusterConnectionId_ = getDefaultInstance().getClusterConnectionId();
      onChanged();
      return this;
    }
    /**
     * <code>string clusterConnectionId = 3;</code>
     * @param value The bytes for clusterConnectionId to set.
     * @return This builder for chaining.
     */
    public Builder setClusterConnectionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clusterConnectionId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.SdkCreateRequest)
  }

  // @@protoc_insertion_point(class_scope:protocol.SdkCreateRequest)
  private static final SdkCreateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SdkCreateRequest();
  }

  public static SdkCreateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SdkCreateRequest>
      PARSER = new com.google.protobuf.AbstractParser<SdkCreateRequest>() {
    @java.lang.Override
    public SdkCreateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SdkCreateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SdkCreateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SdkCreateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public SdkCreateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

