// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_commands.proto

package com.couchbase.grpc.sdk.protocol;

public interface SdkCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.SdkCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protocol.CommandInsert insert = 1;</code>
   * @return Whether the insert field is set.
   */
  boolean hasInsert();
  /**
   * <code>.protocol.CommandInsert insert = 1;</code>
   * @return The insert.
   */
  CommandInsert getInsert();
  /**
   * <code>.protocol.CommandInsert insert = 1;</code>
   */
  CommandInsertOrBuilder getInsertOrBuilder();

  public SdkCommand.CommandCase getCommandCase();
}
