// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_performer.proto

package com.couchbase.grpc.sdk.protocol;

public interface SdkCommandResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.SdkCommandResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protocol.SdkException exception = 1;</code>
   * @return The enum numeric value on the wire for exception.
   */
  int getExceptionValue();
  /**
   * <code>.protocol.SdkException exception = 1;</code>
   * @return The exception.
   */
  com.couchbase.grpc.sdk.protocol.SdkException getException();

  /**
   * <code>.protocol.ExternalException exceptionCause = 2;</code>
   * @return The enum numeric value on the wire for exceptionCause.
   */
  int getExceptionCauseValue();
  /**
   * <code>.protocol.ExternalException exceptionCause = 2;</code>
   * @return The exceptionCause.
   */
  com.couchbase.grpc.sdk.protocol.ExternalException getExceptionCause();

  /**
   * <code>repeated string log = 3;</code>
   * @return A list containing the log.
   */
  java.util.List<java.lang.String>
      getLogList();
  /**
   * <code>repeated string log = 3;</code>
   * @return The count of log.
   */
  int getLogCount();
  /**
   * <code>repeated string log = 3;</code>
   * @param index The index of the element to return.
   * @return The log at the given index.
   */
  java.lang.String getLog(int index);
  /**
   * <code>repeated string log = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the log at the given index.
   */
  com.google.protobuf.ByteString
      getLogBytes(int index);
}
