// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_performer.proto

package com.couchbase.grpc.sdk.protocol;

public interface SdkCreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.SdkCreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .protocol.SdkCommand commands = 1;</code>
   */
  java.util.List<com.couchbase.grpc.sdk.protocol.SdkCommand> 
      getCommandsList();
  /**
   * <code>repeated .protocol.SdkCommand commands = 1;</code>
   */
  com.couchbase.grpc.sdk.protocol.SdkCommand getCommands(int index);
  /**
   * <code>repeated .protocol.SdkCommand commands = 1;</code>
   */
  int getCommandsCount();
  /**
   * <code>repeated .protocol.SdkCommand commands = 1;</code>
   */
  java.util.List<? extends com.couchbase.grpc.sdk.protocol.SdkCommandOrBuilder> 
      getCommandsOrBuilderList();
  /**
   * <code>repeated .protocol.SdkCommand commands = 1;</code>
   */
  com.couchbase.grpc.sdk.protocol.SdkCommandOrBuilder getCommandsOrBuilder(
      int index);

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string clusterConnectionId = 3;</code>
   * @return The clusterConnectionId.
   */
  java.lang.String getClusterConnectionId();
  /**
   * <code>string clusterConnectionId = 3;</code>
   * @return The bytes for clusterConnectionId.
   */
  com.google.protobuf.ByteString
      getClusterConnectionIdBytes();
}
