// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_commands.proto

package com.couchbase.grpc.sdk.protocol;

/**
 * Protobuf enum {@code protocol.SdkException}
 */
public enum SdkException
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NO_EXCEPTION_THROWN = 0;</code>
   */
  NO_EXCEPTION_THROWN(0),
  /**
   * <code>EXCEPTION = 1;</code>
   */
  EXCEPTION(1),
  /**
   * <code>EXCEPTION_UNKNOWN = 2;</code>
   */
  EXCEPTION_UNKNOWN(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NO_EXCEPTION_THROWN = 0;</code>
   */
  public static final int NO_EXCEPTION_THROWN_VALUE = 0;
  /**
   * <code>EXCEPTION = 1;</code>
   */
  public static final int EXCEPTION_VALUE = 1;
  /**
   * <code>EXCEPTION_UNKNOWN = 2;</code>
   */
  public static final int EXCEPTION_UNKNOWN_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SdkException valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SdkException forNumber(int value) {
    switch (value) {
      case 0: return NO_EXCEPTION_THROWN;
      case 1: return EXCEPTION;
      case 2: return EXCEPTION_UNKNOWN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SdkException>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SdkException> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SdkException>() {
          public SdkException findValueByNumber(int number) {
            return SdkException.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return SdkCommands.getDescriptor().getEnumTypes().get(0);
  }

  private static final SdkException[] VALUES = values();

  public static SdkException valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SdkException(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:protocol.SdkException)
}

