// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_performer.proto

package com.couchbase.grpc.sdk.protocol;

/**
 * Protobuf type {@code protocol.SdkFactoryCreateRequest}
 */
public final class SdkFactoryCreateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.SdkFactoryCreateRequest)
    SdkFactoryCreateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SdkFactoryCreateRequest.newBuilder() to construct.
  private SdkFactoryCreateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SdkFactoryCreateRequest() {
    durability_ = 0;
    clusterConnectionId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SdkFactoryCreateRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SdkFactoryCreateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            durability_ = rawValue;
            break;
          }
          case 16: {

            expirationMillis_ = input.readInt32();
            break;
          }
          case 24: {

            cleanupLostAttempts_ = input.readBool();
            break;
          }
          case 32: {

            cleanupClientAttempts_ = input.readBool();
            break;
          }
          case 40: {

            cleanupWindowMillis_ = input.readInt64();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            clusterConnectionId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.couchbase.grpc.sdk.protocol.SdkPerformer.internal_static_protocol_SdkFactoryCreateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.couchbase.grpc.sdk.protocol.SdkPerformer.internal_static_protocol_SdkFactoryCreateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest.class, com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest.Builder.class);
  }

  public static final int DURABILITY_FIELD_NUMBER = 1;
  private int durability_;
  /**
   * <code>.protocol.Durability durability = 1;</code>
   * @return The enum numeric value on the wire for durability.
   */
  @java.lang.Override public int getDurabilityValue() {
    return durability_;
  }
  /**
   * <code>.protocol.Durability durability = 1;</code>
   * @return The durability.
   */
  @java.lang.Override public com.couchbase.grpc.sdk.protocol.Durability getDurability() {
    @SuppressWarnings("deprecation")
    com.couchbase.grpc.sdk.protocol.Durability result = com.couchbase.grpc.sdk.protocol.Durability.valueOf(durability_);
    return result == null ? com.couchbase.grpc.sdk.protocol.Durability.UNRECOGNIZED : result;
  }

  public static final int EXPIRATIONMILLIS_FIELD_NUMBER = 2;
  private int expirationMillis_;
  /**
   * <code>int32 expirationMillis = 2;</code>
   * @return The expirationMillis.
   */
  @java.lang.Override
  public int getExpirationMillis() {
    return expirationMillis_;
  }

  public static final int CLEANUPLOSTATTEMPTS_FIELD_NUMBER = 3;
  private boolean cleanupLostAttempts_;
  /**
   * <pre>
   * Any hooks can only use HookPoints before the CLEANUP_* range
   *repeated Hook hook = 3;
   * </pre>
   *
   * <code>bool cleanupLostAttempts = 3;</code>
   * @return The cleanupLostAttempts.
   */
  @java.lang.Override
  public boolean getCleanupLostAttempts() {
    return cleanupLostAttempts_;
  }

  public static final int CLEANUPCLIENTATTEMPTS_FIELD_NUMBER = 4;
  private boolean cleanupClientAttempts_;
  /**
   * <code>bool cleanupClientAttempts = 4;</code>
   * @return The cleanupClientAttempts.
   */
  @java.lang.Override
  public boolean getCleanupClientAttempts() {
    return cleanupClientAttempts_;
  }

  public static final int CLEANUPWINDOWMILLIS_FIELD_NUMBER = 5;
  private long cleanupWindowMillis_;
  /**
   * <code>int64 cleanupWindowMillis = 5;</code>
   * @return The cleanupWindowMillis.
   */
  @java.lang.Override
  public long getCleanupWindowMillis() {
    return cleanupWindowMillis_;
  }

  public static final int CLUSTERCONNECTIONID_FIELD_NUMBER = 6;
  private volatile java.lang.Object clusterConnectionId_;
  /**
   * <pre>
   *UnstagingMode unstagingMode = 7;
   *Collection metadataCollection = 8;
   * </pre>
   *
   * <code>string clusterConnectionId = 6;</code>
   * @return The clusterConnectionId.
   */
  @java.lang.Override
  public java.lang.String getClusterConnectionId() {
    java.lang.Object ref = clusterConnectionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clusterConnectionId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *UnstagingMode unstagingMode = 7;
   *Collection metadataCollection = 8;
   * </pre>
   *
   * <code>string clusterConnectionId = 6;</code>
   * @return The bytes for clusterConnectionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClusterConnectionIdBytes() {
    java.lang.Object ref = clusterConnectionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clusterConnectionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (durability_ != com.couchbase.grpc.sdk.protocol.Durability.NONE.getNumber()) {
      output.writeEnum(1, durability_);
    }
    if (expirationMillis_ != 0) {
      output.writeInt32(2, expirationMillis_);
    }
    if (cleanupLostAttempts_ != false) {
      output.writeBool(3, cleanupLostAttempts_);
    }
    if (cleanupClientAttempts_ != false) {
      output.writeBool(4, cleanupClientAttempts_);
    }
    if (cleanupWindowMillis_ != 0L) {
      output.writeInt64(5, cleanupWindowMillis_);
    }
    if (!getClusterConnectionIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, clusterConnectionId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (durability_ != com.couchbase.grpc.sdk.protocol.Durability.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, durability_);
    }
    if (expirationMillis_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, expirationMillis_);
    }
    if (cleanupLostAttempts_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, cleanupLostAttempts_);
    }
    if (cleanupClientAttempts_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, cleanupClientAttempts_);
    }
    if (cleanupWindowMillis_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, cleanupWindowMillis_);
    }
    if (!getClusterConnectionIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, clusterConnectionId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest)) {
      return super.equals(obj);
    }
    com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest other = (com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest) obj;

    if (durability_ != other.durability_) return false;
    if (getExpirationMillis()
        != other.getExpirationMillis()) return false;
    if (getCleanupLostAttempts()
        != other.getCleanupLostAttempts()) return false;
    if (getCleanupClientAttempts()
        != other.getCleanupClientAttempts()) return false;
    if (getCleanupWindowMillis()
        != other.getCleanupWindowMillis()) return false;
    if (!getClusterConnectionId()
        .equals(other.getClusterConnectionId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DURABILITY_FIELD_NUMBER;
    hash = (53 * hash) + durability_;
    hash = (37 * hash) + EXPIRATIONMILLIS_FIELD_NUMBER;
    hash = (53 * hash) + getExpirationMillis();
    hash = (37 * hash) + CLEANUPLOSTATTEMPTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCleanupLostAttempts());
    hash = (37 * hash) + CLEANUPCLIENTATTEMPTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCleanupClientAttempts());
    hash = (37 * hash) + CLEANUPWINDOWMILLIS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCleanupWindowMillis());
    hash = (37 * hash) + CLUSTERCONNECTIONID_FIELD_NUMBER;
    hash = (53 * hash) + getClusterConnectionId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.SdkFactoryCreateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.SdkFactoryCreateRequest)
      com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.couchbase.grpc.sdk.protocol.SdkPerformer.internal_static_protocol_SdkFactoryCreateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.couchbase.grpc.sdk.protocol.SdkPerformer.internal_static_protocol_SdkFactoryCreateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest.class, com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest.Builder.class);
    }

    // Construct using com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      durability_ = 0;

      expirationMillis_ = 0;

      cleanupLostAttempts_ = false;

      cleanupClientAttempts_ = false;

      cleanupWindowMillis_ = 0L;

      clusterConnectionId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.couchbase.grpc.sdk.protocol.SdkPerformer.internal_static_protocol_SdkFactoryCreateRequest_descriptor;
    }

    @java.lang.Override
    public com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest getDefaultInstanceForType() {
      return com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest build() {
      com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest buildPartial() {
      com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest result = new com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest(this);
      result.durability_ = durability_;
      result.expirationMillis_ = expirationMillis_;
      result.cleanupLostAttempts_ = cleanupLostAttempts_;
      result.cleanupClientAttempts_ = cleanupClientAttempts_;
      result.cleanupWindowMillis_ = cleanupWindowMillis_;
      result.clusterConnectionId_ = clusterConnectionId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest) {
        return mergeFrom((com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest other) {
      if (other == com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest.getDefaultInstance()) return this;
      if (other.durability_ != 0) {
        setDurabilityValue(other.getDurabilityValue());
      }
      if (other.getExpirationMillis() != 0) {
        setExpirationMillis(other.getExpirationMillis());
      }
      if (other.getCleanupLostAttempts() != false) {
        setCleanupLostAttempts(other.getCleanupLostAttempts());
      }
      if (other.getCleanupClientAttempts() != false) {
        setCleanupClientAttempts(other.getCleanupClientAttempts());
      }
      if (other.getCleanupWindowMillis() != 0L) {
        setCleanupWindowMillis(other.getCleanupWindowMillis());
      }
      if (!other.getClusterConnectionId().isEmpty()) {
        clusterConnectionId_ = other.clusterConnectionId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int durability_ = 0;
    /**
     * <code>.protocol.Durability durability = 1;</code>
     * @return The enum numeric value on the wire for durability.
     */
    @java.lang.Override public int getDurabilityValue() {
      return durability_;
    }
    /**
     * <code>.protocol.Durability durability = 1;</code>
     * @param value The enum numeric value on the wire for durability to set.
     * @return This builder for chaining.
     */
    public Builder setDurabilityValue(int value) {
      
      durability_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.protocol.Durability durability = 1;</code>
     * @return The durability.
     */
    @java.lang.Override
    public com.couchbase.grpc.sdk.protocol.Durability getDurability() {
      @SuppressWarnings("deprecation")
      com.couchbase.grpc.sdk.protocol.Durability result = com.couchbase.grpc.sdk.protocol.Durability.valueOf(durability_);
      return result == null ? com.couchbase.grpc.sdk.protocol.Durability.UNRECOGNIZED : result;
    }
    /**
     * <code>.protocol.Durability durability = 1;</code>
     * @param value The durability to set.
     * @return This builder for chaining.
     */
    public Builder setDurability(com.couchbase.grpc.sdk.protocol.Durability value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      durability_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.protocol.Durability durability = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDurability() {
      
      durability_ = 0;
      onChanged();
      return this;
    }

    private int expirationMillis_ ;
    /**
     * <code>int32 expirationMillis = 2;</code>
     * @return The expirationMillis.
     */
    @java.lang.Override
    public int getExpirationMillis() {
      return expirationMillis_;
    }
    /**
     * <code>int32 expirationMillis = 2;</code>
     * @param value The expirationMillis to set.
     * @return This builder for chaining.
     */
    public Builder setExpirationMillis(int value) {
      
      expirationMillis_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 expirationMillis = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpirationMillis() {
      
      expirationMillis_ = 0;
      onChanged();
      return this;
    }

    private boolean cleanupLostAttempts_ ;
    /**
     * <pre>
     * Any hooks can only use HookPoints before the CLEANUP_* range
     *repeated Hook hook = 3;
     * </pre>
     *
     * <code>bool cleanupLostAttempts = 3;</code>
     * @return The cleanupLostAttempts.
     */
    @java.lang.Override
    public boolean getCleanupLostAttempts() {
      return cleanupLostAttempts_;
    }
    /**
     * <pre>
     * Any hooks can only use HookPoints before the CLEANUP_* range
     *repeated Hook hook = 3;
     * </pre>
     *
     * <code>bool cleanupLostAttempts = 3;</code>
     * @param value The cleanupLostAttempts to set.
     * @return This builder for chaining.
     */
    public Builder setCleanupLostAttempts(boolean value) {
      
      cleanupLostAttempts_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Any hooks can only use HookPoints before the CLEANUP_* range
     *repeated Hook hook = 3;
     * </pre>
     *
     * <code>bool cleanupLostAttempts = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCleanupLostAttempts() {
      
      cleanupLostAttempts_ = false;
      onChanged();
      return this;
    }

    private boolean cleanupClientAttempts_ ;
    /**
     * <code>bool cleanupClientAttempts = 4;</code>
     * @return The cleanupClientAttempts.
     */
    @java.lang.Override
    public boolean getCleanupClientAttempts() {
      return cleanupClientAttempts_;
    }
    /**
     * <code>bool cleanupClientAttempts = 4;</code>
     * @param value The cleanupClientAttempts to set.
     * @return This builder for chaining.
     */
    public Builder setCleanupClientAttempts(boolean value) {
      
      cleanupClientAttempts_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool cleanupClientAttempts = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCleanupClientAttempts() {
      
      cleanupClientAttempts_ = false;
      onChanged();
      return this;
    }

    private long cleanupWindowMillis_ ;
    /**
     * <code>int64 cleanupWindowMillis = 5;</code>
     * @return The cleanupWindowMillis.
     */
    @java.lang.Override
    public long getCleanupWindowMillis() {
      return cleanupWindowMillis_;
    }
    /**
     * <code>int64 cleanupWindowMillis = 5;</code>
     * @param value The cleanupWindowMillis to set.
     * @return This builder for chaining.
     */
    public Builder setCleanupWindowMillis(long value) {
      
      cleanupWindowMillis_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 cleanupWindowMillis = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCleanupWindowMillis() {
      
      cleanupWindowMillis_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object clusterConnectionId_ = "";
    /**
     * <pre>
     *UnstagingMode unstagingMode = 7;
     *Collection metadataCollection = 8;
     * </pre>
     *
     * <code>string clusterConnectionId = 6;</code>
     * @return The clusterConnectionId.
     */
    public java.lang.String getClusterConnectionId() {
      java.lang.Object ref = clusterConnectionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clusterConnectionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *UnstagingMode unstagingMode = 7;
     *Collection metadataCollection = 8;
     * </pre>
     *
     * <code>string clusterConnectionId = 6;</code>
     * @return The bytes for clusterConnectionId.
     */
    public com.google.protobuf.ByteString
        getClusterConnectionIdBytes() {
      java.lang.Object ref = clusterConnectionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusterConnectionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *UnstagingMode unstagingMode = 7;
     *Collection metadataCollection = 8;
     * </pre>
     *
     * <code>string clusterConnectionId = 6;</code>
     * @param value The clusterConnectionId to set.
     * @return This builder for chaining.
     */
    public Builder setClusterConnectionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clusterConnectionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *UnstagingMode unstagingMode = 7;
     *Collection metadataCollection = 8;
     * </pre>
     *
     * <code>string clusterConnectionId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearClusterConnectionId() {
      
      clusterConnectionId_ = getDefaultInstance().getClusterConnectionId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *UnstagingMode unstagingMode = 7;
     *Collection metadataCollection = 8;
     * </pre>
     *
     * <code>string clusterConnectionId = 6;</code>
     * @param value The bytes for clusterConnectionId to set.
     * @return This builder for chaining.
     */
    public Builder setClusterConnectionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clusterConnectionId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.SdkFactoryCreateRequest)
  }

  // @@protoc_insertion_point(class_scope:protocol.SdkFactoryCreateRequest)
  private static final com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest();
  }

  public static com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SdkFactoryCreateRequest>
      PARSER = new com.google.protobuf.AbstractParser<SdkFactoryCreateRequest>() {
    @java.lang.Override
    public SdkFactoryCreateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SdkFactoryCreateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SdkFactoryCreateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SdkFactoryCreateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.couchbase.grpc.sdk.protocol.SdkFactoryCreateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

