// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_performer.proto

package com.couchbase.grpc.sdk.protocol;

public interface SdkFactoryCreateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.SdkFactoryCreateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string SdkFactoryRef = 1;</code>
   * @return The sdkFactoryRef.
   */
  java.lang.String getSdkFactoryRef();
  /**
   * <code>string SdkFactoryRef = 1;</code>
   * @return The bytes for sdkFactoryRef.
   */
  com.google.protobuf.ByteString
      getSdkFactoryRefBytes();
}
