// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_performer.proto

package com.couchbase.grpc.sdk.protocol;

public final class SdkPerformer {
  private SdkPerformer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_CreateConnectionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_CreateConnectionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_CreateConnectionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_CreateConnectionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_SdkAttemptRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_SdkAttemptRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_SdkCreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_SdkCreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_SdkCommandResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_SdkCommandResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_PerfRunHorizontalScaling_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_PerfRunHorizontalScaling_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_PerfRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_PerfRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_PerfSingleSdkOpResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_PerfSingleSdkOpResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023sdk_performer.proto\022\010protocol\032\022sdk_com" +
      "mands.proto\032\017sdk_basic.proto\032\037google/pro" +
      "tobuf/timestamp.proto\032\033google/protobuf/e" +
      "mpty.proto\"\230\001\n\027CreateConnectionRequest\022\027" +
      "\n\017clusterHostname\030\001 \001(\t\022\027\n\017clusterUserna" +
      "me\030\002 \001(\t\022\027\n\017clusterPassword\030\003 \001(\t\022\022\n\nbuc" +
      "ketName\030\004 \001(\t\022\036\n\026useAsDefaultConnection\030" +
      "\005 \001(\010\"\215\001\n\030CreateConnectionResponse\022\032\n\022pe" +
      "rformerUserAgent\030\001 \001(\t\022\037\n\027performerLibra" +
      "ryVersion\030\002 \001(\t\022\027\n\017protocolVersion\030\003 \001(\t" +
      "\022\033\n\023clusterConnectionId\030\004 \001(\t\";\n\021SdkAtte" +
      "mptRequest\022&\n\010commands\030\001 \003(\0132\024.protocol." +
      "SdkCommand\"l\n\020SdkCreateRequest\022-\n\010attemp" +
      "ts\030\001 \003(\0132\033.protocol.SdkAttemptRequest\022\014\n" +
      "\004name\030\002 \001(\t\022\033\n\023clusterConnectionId\030\003 \001(\t" +
      "\"\216\001\n\020SdkCommandResult\022)\n\texception\030\001 \001(\016" +
      "2\026.protocol.SdkException\0223\n\016exceptionCau" +
      "se\030\002 \001(\0162\033.protocol.ExternalException\022\013\n" +
      "\003log\030\003 \003(\t\022\r\n\005sdkId\030\004 \001(\t\"J\n\030PerfRunHori" +
      "zontalScaling\022.\n\nsdkCommand\030\001 \003(\0132\032.prot" +
      "ocol.SdkCreateRequest\"\203\001\n\016PerfRunRequest" +
      "\022\033\n\023clusterConnectionId\030\001 \001(\t\022=\n\021horizon" +
      "talScaling\030\002 \003(\0132\".protocol.PerfRunHoriz" +
      "ontalScaling\022\025\n\rrunForSeconds\030\004 \001(\005\"\241\001\n\025" +
      "PerfSingleSdkOpResult\022+\n\007results\030\001 \001(\0132\032" +
      ".protocol.SdkCommandResult\022-\n\tinitiated\030" +
      "\002 \001(\0132\032.google.protobuf.Timestamp\022,\n\010fin" +
      "ished\030\003 \001(\0132\032.google.protobuf.Timestamp2" +
      "\376\001\n\023PerformerSdkService\022Y\n\020createConnect" +
      "ion\022!.protocol.CreateConnectionRequest\032\"" +
      ".protocol.CreateConnectionResponse\022D\n\nsd" +
      "kCommand\022\032.protocol.SdkCreateRequest\032\032.p" +
      "rotocol.SdkCommandResult\022F\n\007perfRun\022\030.pr" +
      "otocol.PerfRunRequest\032\037.protocol.PerfSin" +
      "gleSdkOpResult0\001B{\n\037com.couchbase.grpc.s" +
      "dk.protocolP\001Z<github.com/couchbaselabs/" +
      "transactions-fit-performer/protocol\252\002\027Co" +
      "uchbase.Grpc.Protocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SdkCommands.getDescriptor(),
          SdkBasic.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_protocol_CreateConnectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_CreateConnectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_CreateConnectionRequest_descriptor,
        new java.lang.String[] { "ClusterHostname", "ClusterUsername", "ClusterPassword", "BucketName", "UseAsDefaultConnection", });
    internal_static_protocol_CreateConnectionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_CreateConnectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_CreateConnectionResponse_descriptor,
        new java.lang.String[] { "PerformerUserAgent", "PerformerLibraryVersion", "ProtocolVersion", "ClusterConnectionId", });
    internal_static_protocol_SdkAttemptRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_SdkAttemptRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_SdkAttemptRequest_descriptor,
        new java.lang.String[] { "Commands", });
    internal_static_protocol_SdkCreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protocol_SdkCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_SdkCreateRequest_descriptor,
        new java.lang.String[] { "Attempts", "Name", "ClusterConnectionId", });
    internal_static_protocol_SdkCommandResult_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protocol_SdkCommandResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_SdkCommandResult_descriptor,
        new java.lang.String[] { "Exception", "ExceptionCause", "Log", "SdkId", });
    internal_static_protocol_PerfRunHorizontalScaling_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_protocol_PerfRunHorizontalScaling_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_PerfRunHorizontalScaling_descriptor,
        new java.lang.String[] { "SdkCommand", });
    internal_static_protocol_PerfRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_protocol_PerfRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_PerfRunRequest_descriptor,
        new java.lang.String[] { "ClusterConnectionId", "HorizontalScaling", "RunForSeconds", });
    internal_static_protocol_PerfSingleSdkOpResult_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_protocol_PerfSingleSdkOpResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_PerfSingleSdkOpResult_descriptor,
        new java.lang.String[] { "Results", "Initiated", "Finished", });
    SdkCommands.getDescriptor();
    SdkBasic.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
