// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk_performer.proto

package com.couchbase.grpc.sdk.protocol;

public final class SdkPerformer {
  private SdkPerformer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_CreateConnectionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_CreateConnectionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_CreateConnectionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_CreateConnectionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_SdkFactoryCreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_SdkFactoryCreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_SdkFactoryCreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_SdkFactoryCreateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023sdk_performer.proto\022\010protocol\"\230\001\n\027Crea" +
      "teConnectionRequest\022\027\n\017clusterHostname\030\001" +
      " \001(\t\022\027\n\017clusterUsername\030\002 \001(\t\022\027\n\017cluster" +
      "Password\030\003 \001(\t\022\022\n\nbucketName\030\004 \001(\t\022\036\n\026us" +
      "eAsDefaultConnection\030\005 \001(\010\"\215\001\n\030CreateCon" +
      "nectionResponse\022\032\n\022performerUserAgent\030\001 " +
      "\001(\t\022\037\n\027performerLibraryVersion\030\002 \001(\t\022\027\n\017" +
      "protocolVersion\030\003 \001(\t\022\033\n\023clusterConnecti" +
      "onId\030\004 \001(\t\"\323\001\n\027SdkFactoryCreateRequest\022(" +
      "\n\ndurability\030\001 \001(\0162\024.protocol.Durability" +
      "\022\030\n\020expirationMillis\030\002 \001(\005\022\033\n\023cleanupLos" +
      "tAttempts\030\003 \001(\010\022\035\n\025cleanupClientAttempts" +
      "\030\004 \001(\010\022\033\n\023cleanupWindowMillis\030\005 \001(\003\022\033\n\023c" +
      "lusterConnectionId\030\006 \001(\t\"1\n\030SdkFactoryCr" +
      "eateResponse\022\025\n\rSdkFactoryRef\030\001 \001(\t*a\n\nD" +
      "urability\022\010\n\004NONE\020\000\022\014\n\010MAJORITY\020\001\022\"\n\036MAJ" +
      "ORITY_AND_PERSIST_TO_ACTIVE\020\002\022\027\n\023PERSIST" +
      "_TO_MAJORITY\020\0032\313\001\n\023PerformerSdkService\022Y" +
      "\n\020createConnection\022!.protocol.CreateConn" +
      "ectionRequest\032\".protocol.CreateConnectio" +
      "nResponse\022Y\n\020sdkFactoryCreate\022!.protocol" +
      ".SdkFactoryCreateRequest\032\".protocol.SdkF" +
      "actoryCreateResponseB{\n\037com.couchbase.gr" +
      "pc.sdk.protocolP\001Z<github.com/couchbasel" +
      "abs/transactions-fit-performer/protocol\252" +
      "\002\027Couchbase.Grpc.Protocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_CreateConnectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_CreateConnectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_CreateConnectionRequest_descriptor,
        new java.lang.String[] { "ClusterHostname", "ClusterUsername", "ClusterPassword", "BucketName", "UseAsDefaultConnection", });
    internal_static_protocol_CreateConnectionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_CreateConnectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_CreateConnectionResponse_descriptor,
        new java.lang.String[] { "PerformerUserAgent", "PerformerLibraryVersion", "ProtocolVersion", "ClusterConnectionId", });
    internal_static_protocol_SdkFactoryCreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_SdkFactoryCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_SdkFactoryCreateRequest_descriptor,
        new java.lang.String[] { "Durability", "ExpirationMillis", "CleanupLostAttempts", "CleanupClientAttempts", "CleanupWindowMillis", "ClusterConnectionId", });
    internal_static_protocol_SdkFactoryCreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protocol_SdkFactoryCreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_SdkFactoryCreateResponse_descriptor,
        new java.lang.String[] { "SdkFactoryRef", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
